################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../include/Rel10/AC-BarringConfig.c \
../include/Rel10/AC-BarringConfig1XRTT-r9.c \
../include/Rel10/ARFCN-ValueCDMA2000.c \
../include/Rel10/ARFCN-ValueEUTRA.c \
../include/Rel10/ARFCN-ValueGERAN.c \
../include/Rel10/ARFCN-ValueUTRA.c \
../include/Rel10/AS-Config.c \
../include/Rel10/AS-Context.c \
../include/Rel10/AbsoluteTimeInfo-r10.c \
../include/Rel10/AccessStratumRelease.c \
../include/Rel10/AdditionalReestabInfo.c \
../include/Rel10/AdditionalReestabInfoList.c \
../include/Rel10/AdditionalSI-Info-r9.c \
../include/Rel10/AdditionalSpectrumEmission.c \
../include/Rel10/AllowedMeasBandwidth.c \
../include/Rel10/AntennaInfoCommon.c \
../include/Rel10/AntennaInfoDedicated-r10.c \
../include/Rel10/AntennaInfoDedicated-v920.c \
../include/Rel10/AntennaInfoDedicated.c \
../include/Rel10/AntennaInfoUL-r10.c \
../include/Rel10/AreaConfiguration-r10.c \
../include/Rel10/BCCH-BCH-Message.c \
../include/Rel10/BCCH-BCH-MessageType.c \
../include/Rel10/BCCH-Config.c \
../include/Rel10/BCCH-DL-SCH-Message.c \
../include/Rel10/BCCH-DL-SCH-MessageType.c \
../include/Rel10/BIT_STRING.c \
../include/Rel10/BOOLEAN.c \
../include/Rel10/BandClassInfoCDMA2000.c \
../include/Rel10/BandClassListCDMA2000.c \
../include/Rel10/BandClassPriority1XRTT.c \
../include/Rel10/BandClassPriorityHRPD.c \
../include/Rel10/BandClassPriorityList1XRTT.c \
../include/Rel10/BandClassPriorityListHRPD.c \
../include/Rel10/BandCombinationListEUTRA-r10.c \
../include/Rel10/BandCombinationParameters-r10.c \
../include/Rel10/BandIndicatorGERAN.c \
../include/Rel10/BandInfoEUTRA.c \
../include/Rel10/BandListEUTRA.c \
../include/Rel10/BandParameters-r10.c \
../include/Rel10/BandParametersDL-r10.c \
../include/Rel10/BandParametersUL-r10.c \
../include/Rel10/BandclassCDMA2000.c \
../include/Rel10/BlackCellsToAddMod.c \
../include/Rel10/BlackCellsToAddModList.c \
../include/Rel10/C-RNTI.c \
../include/Rel10/CA-BandwidthClass-r10.c \
../include/Rel10/CA-MIMO-ParametersDL-r10.c \
../include/Rel10/CA-MIMO-ParametersUL-r10.c \
../include/Rel10/CDMA2000-Type.c \
../include/Rel10/CQI-ReportAperiodic-r10.c \
../include/Rel10/CQI-ReportConfig-r10.c \
../include/Rel10/CQI-ReportConfig-v920.c \
../include/Rel10/CQI-ReportConfig.c \
../include/Rel10/CQI-ReportConfigSCell-r10.c \
../include/Rel10/CQI-ReportModeAperiodic.c \
../include/Rel10/CQI-ReportPeriodic-r10.c \
../include/Rel10/CQI-ReportPeriodic.c \
../include/Rel10/CSFB-RegistrationParam1XRTT-v920.c \
../include/Rel10/CSFB-RegistrationParam1XRTT.c \
../include/Rel10/CSFBParametersRequestCDMA2000-r8-IEs.c \
../include/Rel10/CSFBParametersRequestCDMA2000-v8a0-IEs.c \
../include/Rel10/CSFBParametersRequestCDMA2000.c \
../include/Rel10/CSFBParametersResponseCDMA2000-r8-IEs.c \
../include/Rel10/CSFBParametersResponseCDMA2000-v8a0-IEs.c \
../include/Rel10/CSFBParametersResponseCDMA2000.c \
../include/Rel10/CSG-AllowedReportingCells-r9.c \
../include/Rel10/CSG-Identity.c \
../include/Rel10/CSG-ProximityIndicationParameters-r9.c \
../include/Rel10/CSI-RS-Config-r10.c \
../include/Rel10/CandidateCellInfo-r10.c \
../include/Rel10/CandidateCellInfoList-r10.c \
../include/Rel10/CarrierBandwidthEUTRA.c \
../include/Rel10/CarrierFreqCDMA2000.c \
../include/Rel10/CarrierFreqEUTRA.c \
../include/Rel10/CarrierFreqGERAN.c \
../include/Rel10/CarrierFreqListUTRA-FDD.c \
../include/Rel10/CarrierFreqListUTRA-TDD-r10.c \
../include/Rel10/CarrierFreqListUTRA-TDD.c \
../include/Rel10/CarrierFreqUTRA-FDD.c \
../include/Rel10/CarrierFreqUTRA-TDD.c \
../include/Rel10/CarrierFreqsGERAN.c \
../include/Rel10/CarrierFreqsInfoGERAN.c \
../include/Rel10/CarrierFreqsInfoListGERAN.c \
../include/Rel10/CellChangeOrder.c \
../include/Rel10/CellGlobalIdCDMA2000.c \
../include/Rel10/CellGlobalIdEUTRA.c \
../include/Rel10/CellGlobalIdGERAN.c \
../include/Rel10/CellGlobalIdList-r10.c \
../include/Rel10/CellGlobalIdUTRA.c \
../include/Rel10/CellIdentity.c \
../include/Rel10/CellIndex.c \
../include/Rel10/CellIndexList.c \
../include/Rel10/CellInfoGERAN-r9.c \
../include/Rel10/CellInfoListGERAN-r9.c \
../include/Rel10/CellInfoListUTRA-FDD-r9.c \
../include/Rel10/CellInfoListUTRA-TDD-r10.c \
../include/Rel10/CellInfoListUTRA-TDD-r9.c \
../include/Rel10/CellInfoUTRA-FDD-r9.c \
../include/Rel10/CellInfoUTRA-TDD-r10.c \
../include/Rel10/CellInfoUTRA-TDD-r9.c \
../include/Rel10/CellReselectionParametersCDMA2000-v920.c \
../include/Rel10/CellReselectionParametersCDMA2000.c \
../include/Rel10/CellReselectionPriority.c \
../include/Rel10/CellSelectionInfo-v920.c \
../include/Rel10/CellsToAddMod.c \
../include/Rel10/CellsToAddModCDMA2000.c \
../include/Rel10/CellsToAddModList.c \
../include/Rel10/CellsToAddModListCDMA2000.c \
../include/Rel10/CellsToAddModListUTRA-FDD.c \
../include/Rel10/CellsToAddModListUTRA-TDD.c \
../include/Rel10/CellsToAddModUTRA-FDD.c \
../include/Rel10/CellsToAddModUTRA-TDD.c \
../include/Rel10/CellsTriggeredList.c \
../include/Rel10/CommonSF-AllocPatternList-r9.c \
../include/Rel10/CounterCheck-r8-IEs.c \
../include/Rel10/CounterCheck-v8a0-IEs.c \
../include/Rel10/CounterCheck.c \
../include/Rel10/CounterCheckResponse-r8-IEs.c \
../include/Rel10/CounterCheckResponse-v8a0-IEs.c \
../include/Rel10/CounterCheckResponse.c \
../include/Rel10/CountingRequestInfo-r10.c \
../include/Rel10/CountingRequestList-r10.c \
../include/Rel10/CountingResponseInfo-r10.c \
../include/Rel10/CountingResponseList-r10.c \
../include/Rel10/CrossCarrierSchedulingConfig-r10.c \
../include/Rel10/DL-AM-RLC.c \
../include/Rel10/DL-CCCH-Message.c \
../include/Rel10/DL-CCCH-MessageType.c \
../include/Rel10/DL-DCCH-Message.c \
../include/Rel10/DL-DCCH-MessageType.c \
../include/Rel10/DL-UM-RLC.c \
../include/Rel10/DLInformationTransfer-r8-IEs.c \
../include/Rel10/DLInformationTransfer-v8a0-IEs.c \
../include/Rel10/DLInformationTransfer.c \
../include/Rel10/DRB-CountInfo.c \
../include/Rel10/DRB-CountInfoList.c \
../include/Rel10/DRB-CountMSB-Info.c \
../include/Rel10/DRB-CountMSB-InfoList.c \
../include/Rel10/DRB-Identity.c \
../include/Rel10/DRB-ToAddMod.c \
../include/Rel10/DRB-ToAddModList.c \
../include/Rel10/DRB-ToReleaseList.c \
../include/Rel10/DRX-Config.c \
../include/Rel10/DedicatedInfoCDMA2000.c \
../include/Rel10/DedicatedInfoNAS.c \
../include/Rel10/DeltaFList-PUCCH.c \
../include/Rel10/DeltaTxD-OffsetListPUCCH-r10.c \
../include/Rel10/E-CSFB-r9.c \
../include/Rel10/EstablishmentCause.c \
../include/Rel10/ExplicitListOfARFCNs.c \
../include/Rel10/FilterCoefficient.c \
../include/Rel10/FreqPriorityEUTRA.c \
../include/Rel10/FreqPriorityListEUTRA.c \
../include/Rel10/FreqPriorityListUTRA-FDD.c \
../include/Rel10/FreqPriorityListUTRA-TDD.c \
../include/Rel10/FreqPriorityUTRA-FDD.c \
../include/Rel10/FreqPriorityUTRA-TDD.c \
../include/Rel10/FreqsPriorityGERAN.c \
../include/Rel10/FreqsPriorityListGERAN.c \
../include/Rel10/Handover.c \
../include/Rel10/HandoverCommand-r8-IEs.c \
../include/Rel10/HandoverCommand.c \
../include/Rel10/HandoverFromEUTRAPreparationRequest-r8-IEs.c \
../include/Rel10/HandoverFromEUTRAPreparationRequest-v1020-IEs.c \
../include/Rel10/HandoverFromEUTRAPreparationRequest-v890-IEs.c \
../include/Rel10/HandoverFromEUTRAPreparationRequest-v920-IEs.c \
../include/Rel10/HandoverFromEUTRAPreparationRequest.c \
../include/Rel10/HandoverPreparationInformation-r8-IEs.c \
../include/Rel10/HandoverPreparationInformation-v920-IEs.c \
../include/Rel10/HandoverPreparationInformation.c \
../include/Rel10/Hysteresis.c \
../include/Rel10/IMSI-Digit.c \
../include/Rel10/IMSI.c \
../include/Rel10/INTEGER.c \
../include/Rel10/IRAT-ParametersCDMA2000-1XRTT-v1020.c \
../include/Rel10/IRAT-ParametersCDMA2000-1XRTT-v920.c \
../include/Rel10/IRAT-ParametersCDMA2000-1XRTT.c \
../include/Rel10/IRAT-ParametersCDMA2000-HRPD.c \
../include/Rel10/IRAT-ParametersGERAN-v920.c \
../include/Rel10/IRAT-ParametersGERAN.c \
../include/Rel10/IRAT-ParametersUTRA-FDD.c \
../include/Rel10/IRAT-ParametersUTRA-TDD-v1020.c \
../include/Rel10/IRAT-ParametersUTRA-TDD128.c \
../include/Rel10/IRAT-ParametersUTRA-TDD384.c \
../include/Rel10/IRAT-ParametersUTRA-TDD768.c \
../include/Rel10/IRAT-ParametersUTRA-v920.c \
../include/Rel10/IdleModeMobilityControlInfo.c \
../include/Rel10/InitialUE-Identity.c \
../include/Rel10/InterFreqBandInfo.c \
../include/Rel10/InterFreqBandList.c \
../include/Rel10/InterFreqBlackCellList.c \
../include/Rel10/InterFreqCarrierFreqInfo.c \
../include/Rel10/InterFreqCarrierFreqList.c \
../include/Rel10/InterFreqNeighCellInfo.c \
../include/Rel10/InterFreqNeighCellList.c \
../include/Rel10/InterFreqRSTDMeasurementIndication-r10-IEs.c \
../include/Rel10/InterFreqRSTDMeasurementIndication-r10.c \
../include/Rel10/InterRAT-BandInfo.c \
../include/Rel10/InterRAT-BandList.c \
../include/Rel10/IntraFreqBlackCellList.c \
../include/Rel10/IntraFreqNeighCellInfo.c \
../include/Rel10/IntraFreqNeighCellList.c \
../include/Rel10/Key-eNodeB-Star.c \
../include/Rel10/LocationInfo-r10.c \
../include/Rel10/LogMeasInfo-r10.c \
../include/Rel10/LogMeasInfoList-r10.c \
../include/Rel10/LogMeasReport-r10.c \
../include/Rel10/LoggedMeasurementConfiguration-r10-IEs.c \
../include/Rel10/LoggedMeasurementConfiguration-r10.c \
../include/Rel10/LoggingDuration-r10.c \
../include/Rel10/LoggingInterval-r10.c \
../include/Rel10/LogicalChannelConfig.c \
../include/Rel10/MAC-MainConfig.c \
../include/Rel10/MBMS-NotificationConfig-r9.c \
../include/Rel10/MBMS-SessionInfo-r9.c \
../include/Rel10/MBMS-SessionInfoList-r9.c \
../include/Rel10/MBMSCountingRequest-r10.c \
../include/Rel10/MBMSCountingResponse-r10-IEs.c \
../include/Rel10/MBMSCountingResponse-r10.c \
../include/Rel10/MBSFN-AreaInfo-r9.c \
../include/Rel10/MBSFN-AreaInfoList-r9.c \
../include/Rel10/MBSFN-SubframeConfig.c \
../include/Rel10/MBSFN-SubframeConfigList.c \
../include/Rel10/MBSFNAreaConfiguration-r9.c \
../include/Rel10/MBSFNAreaConfiguration-v930-IEs.c \
../include/Rel10/MCC-MNC-Digit.c \
../include/Rel10/MCC.c \
../include/Rel10/MCCH-Message.c \
../include/Rel10/MCCH-MessageType.c \
../include/Rel10/MIMO-CapabilityDL-r10.c \
../include/Rel10/MIMO-CapabilityUL-r10.c \
../include/Rel10/MMEC.c \
../include/Rel10/MNC.c \
../include/Rel10/MasterInformationBlock.c \
../include/Rel10/MeasConfig.c \
../include/Rel10/MeasCycleSCell-r10.c \
../include/Rel10/MeasGapConfig.c \
../include/Rel10/MeasId.c \
../include/Rel10/MeasIdToAddMod.c \
../include/Rel10/MeasIdToAddModList.c \
../include/Rel10/MeasIdToRemoveList.c \
../include/Rel10/MeasObjectCDMA2000.c \
../include/Rel10/MeasObjectEUTRA.c \
../include/Rel10/MeasObjectGERAN.c \
../include/Rel10/MeasObjectId.c \
../include/Rel10/MeasObjectToAddMod.c \
../include/Rel10/MeasObjectToAddModList.c \
../include/Rel10/MeasObjectToRemoveList.c \
../include/Rel10/MeasObjectUTRA.c \
../include/Rel10/MeasParameters-v1020.c \
../include/Rel10/MeasParameters.c \
../include/Rel10/MeasResult2CDMA2000-r9.c \
../include/Rel10/MeasResult2EUTRA-r9.c \
../include/Rel10/MeasResult2UTRA-r9.c \
../include/Rel10/MeasResultCDMA2000.c \
../include/Rel10/MeasResultEUTRA.c \
../include/Rel10/MeasResultForECID-r9.c \
../include/Rel10/MeasResultGERAN.c \
../include/Rel10/MeasResultList2CDMA2000-r9.c \
../include/Rel10/MeasResultList2EUTRA-r9.c \
../include/Rel10/MeasResultList2GERAN-r10.c \
../include/Rel10/MeasResultList2UTRA-r9.c \
../include/Rel10/MeasResultListCDMA2000.c \
../include/Rel10/MeasResultListEUTRA.c \
../include/Rel10/MeasResultListGERAN.c \
../include/Rel10/MeasResultListUTRA.c \
../include/Rel10/MeasResultServFreq-r10.c \
../include/Rel10/MeasResultServFreqList-r10.c \
../include/Rel10/MeasResultUTRA.c \
../include/Rel10/MeasResults.c \
../include/Rel10/MeasResultsCDMA2000.c \
../include/Rel10/MeasSubframeCellList-r10.c \
../include/Rel10/MeasSubframePattern-r10.c \
../include/Rel10/MeasSubframePatternConfigNeigh-r10.c \
../include/Rel10/MeasSubframePatternPCell-r10.c \
../include/Rel10/MeasurementReport-r8-IEs.c \
../include/Rel10/MeasurementReport-v8a0-IEs.c \
../include/Rel10/MeasurementReport.c \
../include/Rel10/MobilityControlInfo.c \
../include/Rel10/MobilityFromEUTRACommand-r8-IEs.c \
../include/Rel10/MobilityFromEUTRACommand-r9-IEs.c \
../include/Rel10/MobilityFromEUTRACommand-v8a0-IEs.c \
../include/Rel10/MobilityFromEUTRACommand-v8d0-IEs.c \
../include/Rel10/MobilityFromEUTRACommand-v930-IEs.c \
../include/Rel10/MobilityFromEUTRACommand-v960-IEs.c \
../include/Rel10/MobilityFromEUTRACommand.c \
../include/Rel10/MobilityParametersCDMA2000.c \
../include/Rel10/MobilityStateParameters.c \
../include/Rel10/N1PUCCH-AN-CS-r10.c \
../include/Rel10/N1PUCCH-AN-PersistentList.c \
../include/Rel10/NULL.c \
../include/Rel10/NativeEnumerated.c \
../include/Rel10/NativeInteger.c \
../include/Rel10/NeighCellCDMA2000-v920.c \
../include/Rel10/NeighCellCDMA2000.c \
../include/Rel10/NeighCellConfig.c \
../include/Rel10/NeighCellListCDMA2000-v920.c \
../include/Rel10/NeighCellListCDMA2000.c \
../include/Rel10/NeighCellSI-AcquisitionParameters-r9.c \
../include/Rel10/NeighCellsPerBandclassCDMA2000-v920.c \
../include/Rel10/NeighCellsPerBandclassCDMA2000.c \
../include/Rel10/NeighCellsPerBandclassListCDMA2000-v920.c \
../include/Rel10/NeighCellsPerBandclassListCDMA2000.c \
../include/Rel10/NextHopChainingCount.c \
../include/Rel10/NonContiguousUL-RA-WithinCC-List-r10.c \
../include/Rel10/NonContiguousUL-RA-WithinCC-r10.c \
../include/Rel10/OCTET_STRING.c \
../include/Rel10/OtherConfig-r9.c \
../include/Rel10/P-Max.c \
../include/Rel10/PCCH-Config.c \
../include/Rel10/PCCH-Message.c \
../include/Rel10/PCCH-MessageType.c \
../include/Rel10/PDCP-Config.c \
../include/Rel10/PDCP-Parameters.c \
../include/Rel10/PDSCH-ConfigCommon.c \
../include/Rel10/PDSCH-ConfigDedicated.c \
../include/Rel10/PHICH-Config.c \
../include/Rel10/PLMN-Identity.c \
../include/Rel10/PLMN-IdentityInfo.c \
../include/Rel10/PLMN-IdentityList.c \
../include/Rel10/PLMN-IdentityList2.c \
../include/Rel10/PMCH-Config-r9.c \
../include/Rel10/PMCH-Info-r9.c \
../include/Rel10/PMCH-InfoList-r9.c \
../include/Rel10/PRACH-Config.c \
../include/Rel10/PRACH-ConfigInfo.c \
../include/Rel10/PRACH-ConfigSCell-r10.c \
../include/Rel10/PRACH-ConfigSIB.c \
../include/Rel10/PUCCH-ConfigCommon.c \
../include/Rel10/PUCCH-ConfigDedicated-v1020.c \
../include/Rel10/PUCCH-ConfigDedicated.c \
../include/Rel10/PUSCH-ConfigCommon.c \
../include/Rel10/PUSCH-ConfigDedicated-v1020.c \
../include/Rel10/PUSCH-ConfigDedicated.c \
../include/Rel10/PUSCH-ConfigDedicatedSCell-r10.c \
../include/Rel10/Paging-v890-IEs.c \
../include/Rel10/Paging-v920-IEs.c \
../include/Rel10/Paging.c \
../include/Rel10/PagingRecord.c \
../include/Rel10/PagingRecordList.c \
../include/Rel10/PagingUE-Identity.c \
../include/Rel10/PhyLayerParameters-v1020.c \
../include/Rel10/PhyLayerParameters-v920.c \
../include/Rel10/PhyLayerParameters.c \
../include/Rel10/PhysCellId.c \
../include/Rel10/PhysCellIdCDMA2000.c \
../include/Rel10/PhysCellIdGERAN.c \
../include/Rel10/PhysCellIdListCDMA2000-v920.c \
../include/Rel10/PhysCellIdListCDMA2000.c \
../include/Rel10/PhysCellIdRange.c \
../include/Rel10/PhysCellIdRangeUTRA-FDD-r9.c \
../include/Rel10/PhysCellIdRangeUTRA-FDDList-r9.c \
../include/Rel10/PhysCellIdUTRA-FDD.c \
../include/Rel10/PhysCellIdUTRA-TDD.c \
../include/Rel10/PhysicalConfigDedicated.c \
../include/Rel10/PhysicalConfigDedicatedSCell-r10.c \
../include/Rel10/PollByte.c \
../include/Rel10/PollPDU.c \
../include/Rel10/PreRegistrationInfoHRPD.c \
../include/Rel10/PreRegistrationZoneIdHRPD.c \
../include/Rel10/PresenceAntennaPort1.c \
../include/Rel10/ProximityIndication-r9-IEs.c \
../include/Rel10/ProximityIndication-r9.c \
../include/Rel10/ProximityIndication-v930-IEs.c \
../include/Rel10/Q-OffsetRange.c \
../include/Rel10/Q-OffsetRangeInterRAT.c \
../include/Rel10/Q-QualMin-r9.c \
../include/Rel10/Q-RxLevMin.c \
../include/Rel10/QuantityConfig.c \
../include/Rel10/QuantityConfigCDMA2000.c \
../include/Rel10/QuantityConfigEUTRA.c \
../include/Rel10/QuantityConfigGERAN.c \
../include/Rel10/QuantityConfigUTRA-v1020.c \
../include/Rel10/QuantityConfigUTRA.c \
../include/Rel10/RACH-ConfigCommon.c \
../include/Rel10/RACH-ConfigDedicated.c \
../include/Rel10/RAND-CDMA2000.c \
../include/Rel10/RAT-Type.c \
../include/Rel10/RF-Parameters-v1020.c \
../include/Rel10/RF-Parameters.c \
../include/Rel10/RLC-Config.c \
../include/Rel10/RLF-Report-r9.c \
../include/Rel10/RLF-TimersAndConstants-r9.c \
../include/Rel10/RN-SubframeConfig-r10.c \
../include/Rel10/RN-SystemInfo-r10.c \
../include/Rel10/RNReconfiguration-r10-IEs.c \
../include/Rel10/RNReconfiguration-r10.c \
../include/Rel10/RNReconfigurationComplete-r10-IEs.c \
../include/Rel10/RNReconfigurationComplete-r10.c \
../include/Rel10/RRC-TransactionIdentifier.c \
../include/Rel10/RRCConnectionReconfiguration-r8-IEs.c \
../include/Rel10/RRCConnectionReconfiguration-v1020-IEs.c \
../include/Rel10/RRCConnectionReconfiguration-v890-IEs.c \
../include/Rel10/RRCConnectionReconfiguration-v920-IEs.c \
../include/Rel10/RRCConnectionReconfiguration.c \
../include/Rel10/RRCConnectionReconfigurationComplete-r8-IEs.c \
../include/Rel10/RRCConnectionReconfigurationComplete-v1020-IEs.c \
../include/Rel10/RRCConnectionReconfigurationComplete-v8a0-IEs.c \
../include/Rel10/RRCConnectionReconfigurationComplete.c \
../include/Rel10/RRCConnectionReestablishment-r8-IEs.c \
../include/Rel10/RRCConnectionReestablishment-v8a0-IEs.c \
../include/Rel10/RRCConnectionReestablishment.c \
../include/Rel10/RRCConnectionReestablishmentComplete-r8-IEs.c \
../include/Rel10/RRCConnectionReestablishmentComplete-v1020-IEs.c \
../include/Rel10/RRCConnectionReestablishmentComplete-v8a0-IEs.c \
../include/Rel10/RRCConnectionReestablishmentComplete-v920-IEs.c \
../include/Rel10/RRCConnectionReestablishmentComplete.c \
../include/Rel10/RRCConnectionReestablishmentReject-r8-IEs.c \
../include/Rel10/RRCConnectionReestablishmentReject-v8a0-IEs.c \
../include/Rel10/RRCConnectionReestablishmentReject.c \
../include/Rel10/RRCConnectionReestablishmentRequest-r8-IEs.c \
../include/Rel10/RRCConnectionReestablishmentRequest.c \
../include/Rel10/RRCConnectionReject-r8-IEs.c \
../include/Rel10/RRCConnectionReject-v1020-IEs.c \
../include/Rel10/RRCConnectionReject-v8a0-IEs.c \
../include/Rel10/RRCConnectionReject.c \
../include/Rel10/RRCConnectionRelease-r8-IEs.c \
../include/Rel10/RRCConnectionRelease-v1020-IEs.c \
../include/Rel10/RRCConnectionRelease-v890-IEs.c \
../include/Rel10/RRCConnectionRelease-v920-IEs.c \
../include/Rel10/RRCConnectionRelease.c \
../include/Rel10/RRCConnectionRequest-r8-IEs.c \
../include/Rel10/RRCConnectionRequest.c \
../include/Rel10/RRCConnectionSetup-r8-IEs.c \
../include/Rel10/RRCConnectionSetup-v8a0-IEs.c \
../include/Rel10/RRCConnectionSetup.c \
../include/Rel10/RRCConnectionSetupComplete-r8-IEs.c \
../include/Rel10/RRCConnectionSetupComplete-v1020-IEs.c \
../include/Rel10/RRCConnectionSetupComplete-v8a0-IEs.c \
../include/Rel10/RRCConnectionSetupComplete.c \
../include/Rel10/RRM-Config.c \
../include/Rel10/RSRP-Range.c \
../include/Rel10/RSRQ-Range.c \
../include/Rel10/RSTD-InterFreqInfo-r10.c \
../include/Rel10/RSTD-InterFreqInfoList-r10.c \
../include/Rel10/RadioResourceConfigCommon.c \
../include/Rel10/RadioResourceConfigCommonSCell-r10.c \
../include/Rel10/RadioResourceConfigCommonSIB.c \
../include/Rel10/RadioResourceConfigDedicated.c \
../include/Rel10/RadioResourceConfigDedicatedSCell-r10.c \
../include/Rel10/RedirectedCarrierInfo.c \
../include/Rel10/ReestabUE-Identity.c \
../include/Rel10/ReestablishmentCause.c \
../include/Rel10/ReestablishmentInfo.c \
../include/Rel10/RegisteredMME.c \
../include/Rel10/ReleaseCause.c \
../include/Rel10/ReportConfigEUTRA.c \
../include/Rel10/ReportConfigId.c \
../include/Rel10/ReportConfigInterRAT.c \
../include/Rel10/ReportConfigToAddMod.c \
../include/Rel10/ReportConfigToAddModList.c \
../include/Rel10/ReportConfigToRemoveList.c \
../include/Rel10/ReportInterval.c \
../include/Rel10/ReportProximityConfig-r9.c \
../include/Rel10/ReselectionThreshold.c \
../include/Rel10/ReselectionThresholdQ-r9.c \
../include/Rel10/S-TMSI.c \
../include/Rel10/SCellIndex-r10.c \
../include/Rel10/SCellToAddMod-r10.c \
../include/Rel10/SCellToAddModList-r10.c \
../include/Rel10/SCellToReleaseList-r10.c \
../include/Rel10/SI-OrPSI-GERAN.c \
../include/Rel10/SIB-MappingInfo.c \
../include/Rel10/SIB-Type.c \
../include/Rel10/SN-FieldLength.c \
../include/Rel10/SON-Parameters-r9.c \
../include/Rel10/SPS-Config.c \
../include/Rel10/SPS-ConfigDL.c \
../include/Rel10/SPS-ConfigUL.c \
../include/Rel10/SRB-ToAddMod.c \
../include/Rel10/SRB-ToAddModList.c \
../include/Rel10/SRS-ConfigAp-r10.c \
../include/Rel10/SchedulingInfo.c \
../include/Rel10/SchedulingInfoList.c \
../include/Rel10/SchedulingRequestConfig-v1020.c \
../include/Rel10/SchedulingRequestConfig.c \
../include/Rel10/SecondaryPreRegistrationZoneIdListHRPD.c \
../include/Rel10/SecurityAlgorithmConfig.c \
../include/Rel10/SecurityConfigHO.c \
../include/Rel10/SecurityConfigSMC.c \
../include/Rel10/SecurityModeCommand-r8-IEs.c \
../include/Rel10/SecurityModeCommand-v8a0-IEs.c \
../include/Rel10/SecurityModeCommand.c \
../include/Rel10/SecurityModeComplete-r8-IEs.c \
../include/Rel10/SecurityModeComplete-v8a0-IEs.c \
../include/Rel10/SecurityModeComplete.c \
../include/Rel10/SecurityModeFailure-r8-IEs.c \
../include/Rel10/SecurityModeFailure-v8a0-IEs.c \
../include/Rel10/SecurityModeFailure.c \
../include/Rel10/ServCellIndex-r10.c \
../include/Rel10/ShortMAC-I.c \
../include/Rel10/SoundingRS-UL-ConfigCommon.c \
../include/Rel10/SoundingRS-UL-ConfigDedicated-v1020.c \
../include/Rel10/SoundingRS-UL-ConfigDedicated.c \
../include/Rel10/SoundingRS-UL-ConfigDedicatedAperiodic-r10.c \
../include/Rel10/SpeedStateScaleFactors.c \
../include/Rel10/SupportedBandCombination-r10.c \
../include/Rel10/SupportedBandEUTRA.c \
../include/Rel10/SupportedBandGERAN.c \
../include/Rel10/SupportedBandList1XRTT.c \
../include/Rel10/SupportedBandListEUTRA.c \
../include/Rel10/SupportedBandListGERAN.c \
../include/Rel10/SupportedBandListHRPD.c \
../include/Rel10/SupportedBandListUTRA-FDD.c \
../include/Rel10/SupportedBandListUTRA-TDD128.c \
../include/Rel10/SupportedBandListUTRA-TDD384.c \
../include/Rel10/SupportedBandListUTRA-TDD768.c \
../include/Rel10/SupportedBandUTRA-FDD.c \
../include/Rel10/SupportedBandUTRA-TDD128.c \
../include/Rel10/SupportedBandUTRA-TDD384.c \
../include/Rel10/SupportedBandUTRA-TDD768.c \
../include/Rel10/SystemInfoListGERAN.c \
../include/Rel10/SystemInformation-r8-IEs.c \
../include/Rel10/SystemInformation-v8a0-IEs.c \
../include/Rel10/SystemInformation.c \
../include/Rel10/SystemInformationBlockType1-v890-IEs.c \
../include/Rel10/SystemInformationBlockType1-v920-IEs.c \
../include/Rel10/SystemInformationBlockType1.c \
../include/Rel10/SystemInformationBlockType10.c \
../include/Rel10/SystemInformationBlockType11.c \
../include/Rel10/SystemInformationBlockType12-r9.c \
../include/Rel10/SystemInformationBlockType13-r9.c \
../include/Rel10/SystemInformationBlockType2.c \
../include/Rel10/SystemInformationBlockType3.c \
../include/Rel10/SystemInformationBlockType4.c \
../include/Rel10/SystemInformationBlockType5.c \
../include/Rel10/SystemInformationBlockType6.c \
../include/Rel10/SystemInformationBlockType7.c \
../include/Rel10/SystemInformationBlockType8.c \
../include/Rel10/SystemInformationBlockType9.c \
../include/Rel10/SystemTimeInfoCDMA2000.c \
../include/Rel10/T-PollRetransmit.c \
../include/Rel10/T-Reordering.c \
../include/Rel10/T-Reselection.c \
../include/Rel10/T-StatusProhibit.c \
../include/Rel10/TDD-Config.c \
../include/Rel10/TMGI-r9.c \
../include/Rel10/TPC-Index.c \
../include/Rel10/TPC-PDCCH-Config.c \
../include/Rel10/ThresholdCDMA2000.c \
../include/Rel10/ThresholdEUTRA.c \
../include/Rel10/ThresholdGERAN.c \
../include/Rel10/ThresholdUTRA.c \
../include/Rel10/TimeAlignmentTimer.c \
../include/Rel10/TimeToTrigger.c \
../include/Rel10/TraceReference-r10.c \
../include/Rel10/TrackingAreaCode.c \
../include/Rel10/TrackingAreaCodeList-r10.c \
../include/Rel10/UE-BasedNetwPerfMeasParameters-r10.c \
../include/Rel10/UE-CapabilityRAT-Container.c \
../include/Rel10/UE-CapabilityRAT-ContainerList.c \
../include/Rel10/UE-CapabilityRequest.c \
../include/Rel10/UE-EUTRA-Capability-v1020-IEs.c \
../include/Rel10/UE-EUTRA-Capability-v920-IEs.c \
../include/Rel10/UE-EUTRA-Capability-v940-IEs.c \
../include/Rel10/UE-EUTRA-Capability.c \
../include/Rel10/UE-TimersAndConstants.c \
../include/Rel10/UECapabilityEnquiry-r8-IEs.c \
../include/Rel10/UECapabilityEnquiry-v8a0-IEs.c \
../include/Rel10/UECapabilityEnquiry.c \
../include/Rel10/UECapabilityInformation-r8-IEs.c \
../include/Rel10/UECapabilityInformation-v8a0-IEs.c \
../include/Rel10/UECapabilityInformation.c \
../include/Rel10/UEInformationRequest-r9-IEs.c \
../include/Rel10/UEInformationRequest-r9.c \
../include/Rel10/UEInformationRequest-v1020-IEs.c \
../include/Rel10/UEInformationRequest-v930-IEs.c \
../include/Rel10/UEInformationResponse-r9-IEs.c \
../include/Rel10/UEInformationResponse-r9.c \
../include/Rel10/UEInformationResponse-v1020-IEs.c \
../include/Rel10/UEInformationResponse-v930-IEs.c \
../include/Rel10/UERadioAccessCapabilityInformation-r8-IEs.c \
../include/Rel10/UERadioAccessCapabilityInformation.c \
../include/Rel10/UL-AM-RLC.c \
../include/Rel10/UL-CCCH-Message.c \
../include/Rel10/UL-CCCH-MessageType.c \
../include/Rel10/UL-CyclicPrefixLength.c \
../include/Rel10/UL-DCCH-Message.c \
../include/Rel10/UL-DCCH-MessageType.c \
../include/Rel10/UL-ReferenceSignalsPUSCH.c \
../include/Rel10/UL-UM-RLC.c \
../include/Rel10/ULHandoverPreparationTransfer-r8-IEs.c \
../include/Rel10/ULHandoverPreparationTransfer-v8a0-IEs.c \
../include/Rel10/ULHandoverPreparationTransfer.c \
../include/Rel10/ULInformationTransfer-r8-IEs.c \
../include/Rel10/ULInformationTransfer-v8a0-IEs.c \
../include/Rel10/ULInformationTransfer.c \
../include/Rel10/UplinkPowerControlCommon-v1020.c \
../include/Rel10/UplinkPowerControlCommon.c \
../include/Rel10/UplinkPowerControlCommonSCell-r10.c \
../include/Rel10/UplinkPowerControlDedicated-v1020.c \
../include/Rel10/UplinkPowerControlDedicated.c \
../include/Rel10/UplinkPowerControlDedicatedSCell-r10.c \
../include/Rel10/VarLogMeasConfig-r10.c \
../include/Rel10/VarLogMeasReport-r10.c \
../include/Rel10/VarMeasConfig.c \
../include/Rel10/VarMeasReport.c \
../include/Rel10/VarMeasReportList.c \
../include/Rel10/VarRLF-Report-r10.c \
../include/Rel10/VarShortMAC-Input.c \
../include/Rel10/asn_SEQUENCE_OF.c \
../include/Rel10/asn_SET_OF.c \
../include/Rel10/asn_codecs_prim.c \
../include/Rel10/ber_decoder.c \
../include/Rel10/ber_tlv_length.c \
../include/Rel10/ber_tlv_tag.c \
../include/Rel10/constr_CHOICE.c \
../include/Rel10/constr_SEQUENCE.c \
../include/Rel10/constr_SEQUENCE_OF.c \
../include/Rel10/constr_SET_OF.c \
../include/Rel10/constr_TYPE.c \
../include/Rel10/constraints.c \
../include/Rel10/der_encoder.c \
../include/Rel10/per_decoder.c \
../include/Rel10/per_encoder.c \
../include/Rel10/per_opentype.c \
../include/Rel10/per_support.c \
../include/Rel10/xer_decoder.c \
../include/Rel10/xer_encoder.c \
../include/Rel10/xer_support.c 

OBJS += \
./include/Rel10/AC-BarringConfig.o \
./include/Rel10/AC-BarringConfig1XRTT-r9.o \
./include/Rel10/ARFCN-ValueCDMA2000.o \
./include/Rel10/ARFCN-ValueEUTRA.o \
./include/Rel10/ARFCN-ValueGERAN.o \
./include/Rel10/ARFCN-ValueUTRA.o \
./include/Rel10/AS-Config.o \
./include/Rel10/AS-Context.o \
./include/Rel10/AbsoluteTimeInfo-r10.o \
./include/Rel10/AccessStratumRelease.o \
./include/Rel10/AdditionalReestabInfo.o \
./include/Rel10/AdditionalReestabInfoList.o \
./include/Rel10/AdditionalSI-Info-r9.o \
./include/Rel10/AdditionalSpectrumEmission.o \
./include/Rel10/AllowedMeasBandwidth.o \
./include/Rel10/AntennaInfoCommon.o \
./include/Rel10/AntennaInfoDedicated-r10.o \
./include/Rel10/AntennaInfoDedicated-v920.o \
./include/Rel10/AntennaInfoDedicated.o \
./include/Rel10/AntennaInfoUL-r10.o \
./include/Rel10/AreaConfiguration-r10.o \
./include/Rel10/BCCH-BCH-Message.o \
./include/Rel10/BCCH-BCH-MessageType.o \
./include/Rel10/BCCH-Config.o \
./include/Rel10/BCCH-DL-SCH-Message.o \
./include/Rel10/BCCH-DL-SCH-MessageType.o \
./include/Rel10/BIT_STRING.o \
./include/Rel10/BOOLEAN.o \
./include/Rel10/BandClassInfoCDMA2000.o \
./include/Rel10/BandClassListCDMA2000.o \
./include/Rel10/BandClassPriority1XRTT.o \
./include/Rel10/BandClassPriorityHRPD.o \
./include/Rel10/BandClassPriorityList1XRTT.o \
./include/Rel10/BandClassPriorityListHRPD.o \
./include/Rel10/BandCombinationListEUTRA-r10.o \
./include/Rel10/BandCombinationParameters-r10.o \
./include/Rel10/BandIndicatorGERAN.o \
./include/Rel10/BandInfoEUTRA.o \
./include/Rel10/BandListEUTRA.o \
./include/Rel10/BandParameters-r10.o \
./include/Rel10/BandParametersDL-r10.o \
./include/Rel10/BandParametersUL-r10.o \
./include/Rel10/BandclassCDMA2000.o \
./include/Rel10/BlackCellsToAddMod.o \
./include/Rel10/BlackCellsToAddModList.o \
./include/Rel10/C-RNTI.o \
./include/Rel10/CA-BandwidthClass-r10.o \
./include/Rel10/CA-MIMO-ParametersDL-r10.o \
./include/Rel10/CA-MIMO-ParametersUL-r10.o \
./include/Rel10/CDMA2000-Type.o \
./include/Rel10/CQI-ReportAperiodic-r10.o \
./include/Rel10/CQI-ReportConfig-r10.o \
./include/Rel10/CQI-ReportConfig-v920.o \
./include/Rel10/CQI-ReportConfig.o \
./include/Rel10/CQI-ReportConfigSCell-r10.o \
./include/Rel10/CQI-ReportModeAperiodic.o \
./include/Rel10/CQI-ReportPeriodic-r10.o \
./include/Rel10/CQI-ReportPeriodic.o \
./include/Rel10/CSFB-RegistrationParam1XRTT-v920.o \
./include/Rel10/CSFB-RegistrationParam1XRTT.o \
./include/Rel10/CSFBParametersRequestCDMA2000-r8-IEs.o \
./include/Rel10/CSFBParametersRequestCDMA2000-v8a0-IEs.o \
./include/Rel10/CSFBParametersRequestCDMA2000.o \
./include/Rel10/CSFBParametersResponseCDMA2000-r8-IEs.o \
./include/Rel10/CSFBParametersResponseCDMA2000-v8a0-IEs.o \
./include/Rel10/CSFBParametersResponseCDMA2000.o \
./include/Rel10/CSG-AllowedReportingCells-r9.o \
./include/Rel10/CSG-Identity.o \
./include/Rel10/CSG-ProximityIndicationParameters-r9.o \
./include/Rel10/CSI-RS-Config-r10.o \
./include/Rel10/CandidateCellInfo-r10.o \
./include/Rel10/CandidateCellInfoList-r10.o \
./include/Rel10/CarrierBandwidthEUTRA.o \
./include/Rel10/CarrierFreqCDMA2000.o \
./include/Rel10/CarrierFreqEUTRA.o \
./include/Rel10/CarrierFreqGERAN.o \
./include/Rel10/CarrierFreqListUTRA-FDD.o \
./include/Rel10/CarrierFreqListUTRA-TDD-r10.o \
./include/Rel10/CarrierFreqListUTRA-TDD.o \
./include/Rel10/CarrierFreqUTRA-FDD.o \
./include/Rel10/CarrierFreqUTRA-TDD.o \
./include/Rel10/CarrierFreqsGERAN.o \
./include/Rel10/CarrierFreqsInfoGERAN.o \
./include/Rel10/CarrierFreqsInfoListGERAN.o \
./include/Rel10/CellChangeOrder.o \
./include/Rel10/CellGlobalIdCDMA2000.o \
./include/Rel10/CellGlobalIdEUTRA.o \
./include/Rel10/CellGlobalIdGERAN.o \
./include/Rel10/CellGlobalIdList-r10.o \
./include/Rel10/CellGlobalIdUTRA.o \
./include/Rel10/CellIdentity.o \
./include/Rel10/CellIndex.o \
./include/Rel10/CellIndexList.o \
./include/Rel10/CellInfoGERAN-r9.o \
./include/Rel10/CellInfoListGERAN-r9.o \
./include/Rel10/CellInfoListUTRA-FDD-r9.o \
./include/Rel10/CellInfoListUTRA-TDD-r10.o \
./include/Rel10/CellInfoListUTRA-TDD-r9.o \
./include/Rel10/CellInfoUTRA-FDD-r9.o \
./include/Rel10/CellInfoUTRA-TDD-r10.o \
./include/Rel10/CellInfoUTRA-TDD-r9.o \
./include/Rel10/CellReselectionParametersCDMA2000-v920.o \
./include/Rel10/CellReselectionParametersCDMA2000.o \
./include/Rel10/CellReselectionPriority.o \
./include/Rel10/CellSelectionInfo-v920.o \
./include/Rel10/CellsToAddMod.o \
./include/Rel10/CellsToAddModCDMA2000.o \
./include/Rel10/CellsToAddModList.o \
./include/Rel10/CellsToAddModListCDMA2000.o \
./include/Rel10/CellsToAddModListUTRA-FDD.o \
./include/Rel10/CellsToAddModListUTRA-TDD.o \
./include/Rel10/CellsToAddModUTRA-FDD.o \
./include/Rel10/CellsToAddModUTRA-TDD.o \
./include/Rel10/CellsTriggeredList.o \
./include/Rel10/CommonSF-AllocPatternList-r9.o \
./include/Rel10/CounterCheck-r8-IEs.o \
./include/Rel10/CounterCheck-v8a0-IEs.o \
./include/Rel10/CounterCheck.o \
./include/Rel10/CounterCheckResponse-r8-IEs.o \
./include/Rel10/CounterCheckResponse-v8a0-IEs.o \
./include/Rel10/CounterCheckResponse.o \
./include/Rel10/CountingRequestInfo-r10.o \
./include/Rel10/CountingRequestList-r10.o \
./include/Rel10/CountingResponseInfo-r10.o \
./include/Rel10/CountingResponseList-r10.o \
./include/Rel10/CrossCarrierSchedulingConfig-r10.o \
./include/Rel10/DL-AM-RLC.o \
./include/Rel10/DL-CCCH-Message.o \
./include/Rel10/DL-CCCH-MessageType.o \
./include/Rel10/DL-DCCH-Message.o \
./include/Rel10/DL-DCCH-MessageType.o \
./include/Rel10/DL-UM-RLC.o \
./include/Rel10/DLInformationTransfer-r8-IEs.o \
./include/Rel10/DLInformationTransfer-v8a0-IEs.o \
./include/Rel10/DLInformationTransfer.o \
./include/Rel10/DRB-CountInfo.o \
./include/Rel10/DRB-CountInfoList.o \
./include/Rel10/DRB-CountMSB-Info.o \
./include/Rel10/DRB-CountMSB-InfoList.o \
./include/Rel10/DRB-Identity.o \
./include/Rel10/DRB-ToAddMod.o \
./include/Rel10/DRB-ToAddModList.o \
./include/Rel10/DRB-ToReleaseList.o \
./include/Rel10/DRX-Config.o \
./include/Rel10/DedicatedInfoCDMA2000.o \
./include/Rel10/DedicatedInfoNAS.o \
./include/Rel10/DeltaFList-PUCCH.o \
./include/Rel10/DeltaTxD-OffsetListPUCCH-r10.o \
./include/Rel10/E-CSFB-r9.o \
./include/Rel10/EstablishmentCause.o \
./include/Rel10/ExplicitListOfARFCNs.o \
./include/Rel10/FilterCoefficient.o \
./include/Rel10/FreqPriorityEUTRA.o \
./include/Rel10/FreqPriorityListEUTRA.o \
./include/Rel10/FreqPriorityListUTRA-FDD.o \
./include/Rel10/FreqPriorityListUTRA-TDD.o \
./include/Rel10/FreqPriorityUTRA-FDD.o \
./include/Rel10/FreqPriorityUTRA-TDD.o \
./include/Rel10/FreqsPriorityGERAN.o \
./include/Rel10/FreqsPriorityListGERAN.o \
./include/Rel10/Handover.o \
./include/Rel10/HandoverCommand-r8-IEs.o \
./include/Rel10/HandoverCommand.o \
./include/Rel10/HandoverFromEUTRAPreparationRequest-r8-IEs.o \
./include/Rel10/HandoverFromEUTRAPreparationRequest-v1020-IEs.o \
./include/Rel10/HandoverFromEUTRAPreparationRequest-v890-IEs.o \
./include/Rel10/HandoverFromEUTRAPreparationRequest-v920-IEs.o \
./include/Rel10/HandoverFromEUTRAPreparationRequest.o \
./include/Rel10/HandoverPreparationInformation-r8-IEs.o \
./include/Rel10/HandoverPreparationInformation-v920-IEs.o \
./include/Rel10/HandoverPreparationInformation.o \
./include/Rel10/Hysteresis.o \
./include/Rel10/IMSI-Digit.o \
./include/Rel10/IMSI.o \
./include/Rel10/INTEGER.o \
./include/Rel10/IRAT-ParametersCDMA2000-1XRTT-v1020.o \
./include/Rel10/IRAT-ParametersCDMA2000-1XRTT-v920.o \
./include/Rel10/IRAT-ParametersCDMA2000-1XRTT.o \
./include/Rel10/IRAT-ParametersCDMA2000-HRPD.o \
./include/Rel10/IRAT-ParametersGERAN-v920.o \
./include/Rel10/IRAT-ParametersGERAN.o \
./include/Rel10/IRAT-ParametersUTRA-FDD.o \
./include/Rel10/IRAT-ParametersUTRA-TDD-v1020.o \
./include/Rel10/IRAT-ParametersUTRA-TDD128.o \
./include/Rel10/IRAT-ParametersUTRA-TDD384.o \
./include/Rel10/IRAT-ParametersUTRA-TDD768.o \
./include/Rel10/IRAT-ParametersUTRA-v920.o \
./include/Rel10/IdleModeMobilityControlInfo.o \
./include/Rel10/InitialUE-Identity.o \
./include/Rel10/InterFreqBandInfo.o \
./include/Rel10/InterFreqBandList.o \
./include/Rel10/InterFreqBlackCellList.o \
./include/Rel10/InterFreqCarrierFreqInfo.o \
./include/Rel10/InterFreqCarrierFreqList.o \
./include/Rel10/InterFreqNeighCellInfo.o \
./include/Rel10/InterFreqNeighCellList.o \
./include/Rel10/InterFreqRSTDMeasurementIndication-r10-IEs.o \
./include/Rel10/InterFreqRSTDMeasurementIndication-r10.o \
./include/Rel10/InterRAT-BandInfo.o \
./include/Rel10/InterRAT-BandList.o \
./include/Rel10/IntraFreqBlackCellList.o \
./include/Rel10/IntraFreqNeighCellInfo.o \
./include/Rel10/IntraFreqNeighCellList.o \
./include/Rel10/Key-eNodeB-Star.o \
./include/Rel10/LocationInfo-r10.o \
./include/Rel10/LogMeasInfo-r10.o \
./include/Rel10/LogMeasInfoList-r10.o \
./include/Rel10/LogMeasReport-r10.o \
./include/Rel10/LoggedMeasurementConfiguration-r10-IEs.o \
./include/Rel10/LoggedMeasurementConfiguration-r10.o \
./include/Rel10/LoggingDuration-r10.o \
./include/Rel10/LoggingInterval-r10.o \
./include/Rel10/LogicalChannelConfig.o \
./include/Rel10/MAC-MainConfig.o \
./include/Rel10/MBMS-NotificationConfig-r9.o \
./include/Rel10/MBMS-SessionInfo-r9.o \
./include/Rel10/MBMS-SessionInfoList-r9.o \
./include/Rel10/MBMSCountingRequest-r10.o \
./include/Rel10/MBMSCountingResponse-r10-IEs.o \
./include/Rel10/MBMSCountingResponse-r10.o \
./include/Rel10/MBSFN-AreaInfo-r9.o \
./include/Rel10/MBSFN-AreaInfoList-r9.o \
./include/Rel10/MBSFN-SubframeConfig.o \
./include/Rel10/MBSFN-SubframeConfigList.o \
./include/Rel10/MBSFNAreaConfiguration-r9.o \
./include/Rel10/MBSFNAreaConfiguration-v930-IEs.o \
./include/Rel10/MCC-MNC-Digit.o \
./include/Rel10/MCC.o \
./include/Rel10/MCCH-Message.o \
./include/Rel10/MCCH-MessageType.o \
./include/Rel10/MIMO-CapabilityDL-r10.o \
./include/Rel10/MIMO-CapabilityUL-r10.o \
./include/Rel10/MMEC.o \
./include/Rel10/MNC.o \
./include/Rel10/MasterInformationBlock.o \
./include/Rel10/MeasConfig.o \
./include/Rel10/MeasCycleSCell-r10.o \
./include/Rel10/MeasGapConfig.o \
./include/Rel10/MeasId.o \
./include/Rel10/MeasIdToAddMod.o \
./include/Rel10/MeasIdToAddModList.o \
./include/Rel10/MeasIdToRemoveList.o \
./include/Rel10/MeasObjectCDMA2000.o \
./include/Rel10/MeasObjectEUTRA.o \
./include/Rel10/MeasObjectGERAN.o \
./include/Rel10/MeasObjectId.o \
./include/Rel10/MeasObjectToAddMod.o \
./include/Rel10/MeasObjectToAddModList.o \
./include/Rel10/MeasObjectToRemoveList.o \
./include/Rel10/MeasObjectUTRA.o \
./include/Rel10/MeasParameters-v1020.o \
./include/Rel10/MeasParameters.o \
./include/Rel10/MeasResult2CDMA2000-r9.o \
./include/Rel10/MeasResult2EUTRA-r9.o \
./include/Rel10/MeasResult2UTRA-r9.o \
./include/Rel10/MeasResultCDMA2000.o \
./include/Rel10/MeasResultEUTRA.o \
./include/Rel10/MeasResultForECID-r9.o \
./include/Rel10/MeasResultGERAN.o \
./include/Rel10/MeasResultList2CDMA2000-r9.o \
./include/Rel10/MeasResultList2EUTRA-r9.o \
./include/Rel10/MeasResultList2GERAN-r10.o \
./include/Rel10/MeasResultList2UTRA-r9.o \
./include/Rel10/MeasResultListCDMA2000.o \
./include/Rel10/MeasResultListEUTRA.o \
./include/Rel10/MeasResultListGERAN.o \
./include/Rel10/MeasResultListUTRA.o \
./include/Rel10/MeasResultServFreq-r10.o \
./include/Rel10/MeasResultServFreqList-r10.o \
./include/Rel10/MeasResultUTRA.o \
./include/Rel10/MeasResults.o \
./include/Rel10/MeasResultsCDMA2000.o \
./include/Rel10/MeasSubframeCellList-r10.o \
./include/Rel10/MeasSubframePattern-r10.o \
./include/Rel10/MeasSubframePatternConfigNeigh-r10.o \
./include/Rel10/MeasSubframePatternPCell-r10.o \
./include/Rel10/MeasurementReport-r8-IEs.o \
./include/Rel10/MeasurementReport-v8a0-IEs.o \
./include/Rel10/MeasurementReport.o \
./include/Rel10/MobilityControlInfo.o \
./include/Rel10/MobilityFromEUTRACommand-r8-IEs.o \
./include/Rel10/MobilityFromEUTRACommand-r9-IEs.o \
./include/Rel10/MobilityFromEUTRACommand-v8a0-IEs.o \
./include/Rel10/MobilityFromEUTRACommand-v8d0-IEs.o \
./include/Rel10/MobilityFromEUTRACommand-v930-IEs.o \
./include/Rel10/MobilityFromEUTRACommand-v960-IEs.o \
./include/Rel10/MobilityFromEUTRACommand.o \
./include/Rel10/MobilityParametersCDMA2000.o \
./include/Rel10/MobilityStateParameters.o \
./include/Rel10/N1PUCCH-AN-CS-r10.o \
./include/Rel10/N1PUCCH-AN-PersistentList.o \
./include/Rel10/NULL.o \
./include/Rel10/NativeEnumerated.o \
./include/Rel10/NativeInteger.o \
./include/Rel10/NeighCellCDMA2000-v920.o \
./include/Rel10/NeighCellCDMA2000.o \
./include/Rel10/NeighCellConfig.o \
./include/Rel10/NeighCellListCDMA2000-v920.o \
./include/Rel10/NeighCellListCDMA2000.o \
./include/Rel10/NeighCellSI-AcquisitionParameters-r9.o \
./include/Rel10/NeighCellsPerBandclassCDMA2000-v920.o \
./include/Rel10/NeighCellsPerBandclassCDMA2000.o \
./include/Rel10/NeighCellsPerBandclassListCDMA2000-v920.o \
./include/Rel10/NeighCellsPerBandclassListCDMA2000.o \
./include/Rel10/NextHopChainingCount.o \
./include/Rel10/NonContiguousUL-RA-WithinCC-List-r10.o \
./include/Rel10/NonContiguousUL-RA-WithinCC-r10.o \
./include/Rel10/OCTET_STRING.o \
./include/Rel10/OtherConfig-r9.o \
./include/Rel10/P-Max.o \
./include/Rel10/PCCH-Config.o \
./include/Rel10/PCCH-Message.o \
./include/Rel10/PCCH-MessageType.o \
./include/Rel10/PDCP-Config.o \
./include/Rel10/PDCP-Parameters.o \
./include/Rel10/PDSCH-ConfigCommon.o \
./include/Rel10/PDSCH-ConfigDedicated.o \
./include/Rel10/PHICH-Config.o \
./include/Rel10/PLMN-Identity.o \
./include/Rel10/PLMN-IdentityInfo.o \
./include/Rel10/PLMN-IdentityList.o \
./include/Rel10/PLMN-IdentityList2.o \
./include/Rel10/PMCH-Config-r9.o \
./include/Rel10/PMCH-Info-r9.o \
./include/Rel10/PMCH-InfoList-r9.o \
./include/Rel10/PRACH-Config.o \
./include/Rel10/PRACH-ConfigInfo.o \
./include/Rel10/PRACH-ConfigSCell-r10.o \
./include/Rel10/PRACH-ConfigSIB.o \
./include/Rel10/PUCCH-ConfigCommon.o \
./include/Rel10/PUCCH-ConfigDedicated-v1020.o \
./include/Rel10/PUCCH-ConfigDedicated.o \
./include/Rel10/PUSCH-ConfigCommon.o \
./include/Rel10/PUSCH-ConfigDedicated-v1020.o \
./include/Rel10/PUSCH-ConfigDedicated.o \
./include/Rel10/PUSCH-ConfigDedicatedSCell-r10.o \
./include/Rel10/Paging-v890-IEs.o \
./include/Rel10/Paging-v920-IEs.o \
./include/Rel10/Paging.o \
./include/Rel10/PagingRecord.o \
./include/Rel10/PagingRecordList.o \
./include/Rel10/PagingUE-Identity.o \
./include/Rel10/PhyLayerParameters-v1020.o \
./include/Rel10/PhyLayerParameters-v920.o \
./include/Rel10/PhyLayerParameters.o \
./include/Rel10/PhysCellId.o \
./include/Rel10/PhysCellIdCDMA2000.o \
./include/Rel10/PhysCellIdGERAN.o \
./include/Rel10/PhysCellIdListCDMA2000-v920.o \
./include/Rel10/PhysCellIdListCDMA2000.o \
./include/Rel10/PhysCellIdRange.o \
./include/Rel10/PhysCellIdRangeUTRA-FDD-r9.o \
./include/Rel10/PhysCellIdRangeUTRA-FDDList-r9.o \
./include/Rel10/PhysCellIdUTRA-FDD.o \
./include/Rel10/PhysCellIdUTRA-TDD.o \
./include/Rel10/PhysicalConfigDedicated.o \
./include/Rel10/PhysicalConfigDedicatedSCell-r10.o \
./include/Rel10/PollByte.o \
./include/Rel10/PollPDU.o \
./include/Rel10/PreRegistrationInfoHRPD.o \
./include/Rel10/PreRegistrationZoneIdHRPD.o \
./include/Rel10/PresenceAntennaPort1.o \
./include/Rel10/ProximityIndication-r9-IEs.o \
./include/Rel10/ProximityIndication-r9.o \
./include/Rel10/ProximityIndication-v930-IEs.o \
./include/Rel10/Q-OffsetRange.o \
./include/Rel10/Q-OffsetRangeInterRAT.o \
./include/Rel10/Q-QualMin-r9.o \
./include/Rel10/Q-RxLevMin.o \
./include/Rel10/QuantityConfig.o \
./include/Rel10/QuantityConfigCDMA2000.o \
./include/Rel10/QuantityConfigEUTRA.o \
./include/Rel10/QuantityConfigGERAN.o \
./include/Rel10/QuantityConfigUTRA-v1020.o \
./include/Rel10/QuantityConfigUTRA.o \
./include/Rel10/RACH-ConfigCommon.o \
./include/Rel10/RACH-ConfigDedicated.o \
./include/Rel10/RAND-CDMA2000.o \
./include/Rel10/RAT-Type.o \
./include/Rel10/RF-Parameters-v1020.o \
./include/Rel10/RF-Parameters.o \
./include/Rel10/RLC-Config.o \
./include/Rel10/RLF-Report-r9.o \
./include/Rel10/RLF-TimersAndConstants-r9.o \
./include/Rel10/RN-SubframeConfig-r10.o \
./include/Rel10/RN-SystemInfo-r10.o \
./include/Rel10/RNReconfiguration-r10-IEs.o \
./include/Rel10/RNReconfiguration-r10.o \
./include/Rel10/RNReconfigurationComplete-r10-IEs.o \
./include/Rel10/RNReconfigurationComplete-r10.o \
./include/Rel10/RRC-TransactionIdentifier.o \
./include/Rel10/RRCConnectionReconfiguration-r8-IEs.o \
./include/Rel10/RRCConnectionReconfiguration-v1020-IEs.o \
./include/Rel10/RRCConnectionReconfiguration-v890-IEs.o \
./include/Rel10/RRCConnectionReconfiguration-v920-IEs.o \
./include/Rel10/RRCConnectionReconfiguration.o \
./include/Rel10/RRCConnectionReconfigurationComplete-r8-IEs.o \
./include/Rel10/RRCConnectionReconfigurationComplete-v1020-IEs.o \
./include/Rel10/RRCConnectionReconfigurationComplete-v8a0-IEs.o \
./include/Rel10/RRCConnectionReconfigurationComplete.o \
./include/Rel10/RRCConnectionReestablishment-r8-IEs.o \
./include/Rel10/RRCConnectionReestablishment-v8a0-IEs.o \
./include/Rel10/RRCConnectionReestablishment.o \
./include/Rel10/RRCConnectionReestablishmentComplete-r8-IEs.o \
./include/Rel10/RRCConnectionReestablishmentComplete-v1020-IEs.o \
./include/Rel10/RRCConnectionReestablishmentComplete-v8a0-IEs.o \
./include/Rel10/RRCConnectionReestablishmentComplete-v920-IEs.o \
./include/Rel10/RRCConnectionReestablishmentComplete.o \
./include/Rel10/RRCConnectionReestablishmentReject-r8-IEs.o \
./include/Rel10/RRCConnectionReestablishmentReject-v8a0-IEs.o \
./include/Rel10/RRCConnectionReestablishmentReject.o \
./include/Rel10/RRCConnectionReestablishmentRequest-r8-IEs.o \
./include/Rel10/RRCConnectionReestablishmentRequest.o \
./include/Rel10/RRCConnectionReject-r8-IEs.o \
./include/Rel10/RRCConnectionReject-v1020-IEs.o \
./include/Rel10/RRCConnectionReject-v8a0-IEs.o \
./include/Rel10/RRCConnectionReject.o \
./include/Rel10/RRCConnectionRelease-r8-IEs.o \
./include/Rel10/RRCConnectionRelease-v1020-IEs.o \
./include/Rel10/RRCConnectionRelease-v890-IEs.o \
./include/Rel10/RRCConnectionRelease-v920-IEs.o \
./include/Rel10/RRCConnectionRelease.o \
./include/Rel10/RRCConnectionRequest-r8-IEs.o \
./include/Rel10/RRCConnectionRequest.o \
./include/Rel10/RRCConnectionSetup-r8-IEs.o \
./include/Rel10/RRCConnectionSetup-v8a0-IEs.o \
./include/Rel10/RRCConnectionSetup.o \
./include/Rel10/RRCConnectionSetupComplete-r8-IEs.o \
./include/Rel10/RRCConnectionSetupComplete-v1020-IEs.o \
./include/Rel10/RRCConnectionSetupComplete-v8a0-IEs.o \
./include/Rel10/RRCConnectionSetupComplete.o \
./include/Rel10/RRM-Config.o \
./include/Rel10/RSRP-Range.o \
./include/Rel10/RSRQ-Range.o \
./include/Rel10/RSTD-InterFreqInfo-r10.o \
./include/Rel10/RSTD-InterFreqInfoList-r10.o \
./include/Rel10/RadioResourceConfigCommon.o \
./include/Rel10/RadioResourceConfigCommonSCell-r10.o \
./include/Rel10/RadioResourceConfigCommonSIB.o \
./include/Rel10/RadioResourceConfigDedicated.o \
./include/Rel10/RadioResourceConfigDedicatedSCell-r10.o \
./include/Rel10/RedirectedCarrierInfo.o \
./include/Rel10/ReestabUE-Identity.o \
./include/Rel10/ReestablishmentCause.o \
./include/Rel10/ReestablishmentInfo.o \
./include/Rel10/RegisteredMME.o \
./include/Rel10/ReleaseCause.o \
./include/Rel10/ReportConfigEUTRA.o \
./include/Rel10/ReportConfigId.o \
./include/Rel10/ReportConfigInterRAT.o \
./include/Rel10/ReportConfigToAddMod.o \
./include/Rel10/ReportConfigToAddModList.o \
./include/Rel10/ReportConfigToRemoveList.o \
./include/Rel10/ReportInterval.o \
./include/Rel10/ReportProximityConfig-r9.o \
./include/Rel10/ReselectionThreshold.o \
./include/Rel10/ReselectionThresholdQ-r9.o \
./include/Rel10/S-TMSI.o \
./include/Rel10/SCellIndex-r10.o \
./include/Rel10/SCellToAddMod-r10.o \
./include/Rel10/SCellToAddModList-r10.o \
./include/Rel10/SCellToReleaseList-r10.o \
./include/Rel10/SI-OrPSI-GERAN.o \
./include/Rel10/SIB-MappingInfo.o \
./include/Rel10/SIB-Type.o \
./include/Rel10/SN-FieldLength.o \
./include/Rel10/SON-Parameters-r9.o \
./include/Rel10/SPS-Config.o \
./include/Rel10/SPS-ConfigDL.o \
./include/Rel10/SPS-ConfigUL.o \
./include/Rel10/SRB-ToAddMod.o \
./include/Rel10/SRB-ToAddModList.o \
./include/Rel10/SRS-ConfigAp-r10.o \
./include/Rel10/SchedulingInfo.o \
./include/Rel10/SchedulingInfoList.o \
./include/Rel10/SchedulingRequestConfig-v1020.o \
./include/Rel10/SchedulingRequestConfig.o \
./include/Rel10/SecondaryPreRegistrationZoneIdListHRPD.o \
./include/Rel10/SecurityAlgorithmConfig.o \
./include/Rel10/SecurityConfigHO.o \
./include/Rel10/SecurityConfigSMC.o \
./include/Rel10/SecurityModeCommand-r8-IEs.o \
./include/Rel10/SecurityModeCommand-v8a0-IEs.o \
./include/Rel10/SecurityModeCommand.o \
./include/Rel10/SecurityModeComplete-r8-IEs.o \
./include/Rel10/SecurityModeComplete-v8a0-IEs.o \
./include/Rel10/SecurityModeComplete.o \
./include/Rel10/SecurityModeFailure-r8-IEs.o \
./include/Rel10/SecurityModeFailure-v8a0-IEs.o \
./include/Rel10/SecurityModeFailure.o \
./include/Rel10/ServCellIndex-r10.o \
./include/Rel10/ShortMAC-I.o \
./include/Rel10/SoundingRS-UL-ConfigCommon.o \
./include/Rel10/SoundingRS-UL-ConfigDedicated-v1020.o \
./include/Rel10/SoundingRS-UL-ConfigDedicated.o \
./include/Rel10/SoundingRS-UL-ConfigDedicatedAperiodic-r10.o \
./include/Rel10/SpeedStateScaleFactors.o \
./include/Rel10/SupportedBandCombination-r10.o \
./include/Rel10/SupportedBandEUTRA.o \
./include/Rel10/SupportedBandGERAN.o \
./include/Rel10/SupportedBandList1XRTT.o \
./include/Rel10/SupportedBandListEUTRA.o \
./include/Rel10/SupportedBandListGERAN.o \
./include/Rel10/SupportedBandListHRPD.o \
./include/Rel10/SupportedBandListUTRA-FDD.o \
./include/Rel10/SupportedBandListUTRA-TDD128.o \
./include/Rel10/SupportedBandListUTRA-TDD384.o \
./include/Rel10/SupportedBandListUTRA-TDD768.o \
./include/Rel10/SupportedBandUTRA-FDD.o \
./include/Rel10/SupportedBandUTRA-TDD128.o \
./include/Rel10/SupportedBandUTRA-TDD384.o \
./include/Rel10/SupportedBandUTRA-TDD768.o \
./include/Rel10/SystemInfoListGERAN.o \
./include/Rel10/SystemInformation-r8-IEs.o \
./include/Rel10/SystemInformation-v8a0-IEs.o \
./include/Rel10/SystemInformation.o \
./include/Rel10/SystemInformationBlockType1-v890-IEs.o \
./include/Rel10/SystemInformationBlockType1-v920-IEs.o \
./include/Rel10/SystemInformationBlockType1.o \
./include/Rel10/SystemInformationBlockType10.o \
./include/Rel10/SystemInformationBlockType11.o \
./include/Rel10/SystemInformationBlockType12-r9.o \
./include/Rel10/SystemInformationBlockType13-r9.o \
./include/Rel10/SystemInformationBlockType2.o \
./include/Rel10/SystemInformationBlockType3.o \
./include/Rel10/SystemInformationBlockType4.o \
./include/Rel10/SystemInformationBlockType5.o \
./include/Rel10/SystemInformationBlockType6.o \
./include/Rel10/SystemInformationBlockType7.o \
./include/Rel10/SystemInformationBlockType8.o \
./include/Rel10/SystemInformationBlockType9.o \
./include/Rel10/SystemTimeInfoCDMA2000.o \
./include/Rel10/T-PollRetransmit.o \
./include/Rel10/T-Reordering.o \
./include/Rel10/T-Reselection.o \
./include/Rel10/T-StatusProhibit.o \
./include/Rel10/TDD-Config.o \
./include/Rel10/TMGI-r9.o \
./include/Rel10/TPC-Index.o \
./include/Rel10/TPC-PDCCH-Config.o \
./include/Rel10/ThresholdCDMA2000.o \
./include/Rel10/ThresholdEUTRA.o \
./include/Rel10/ThresholdGERAN.o \
./include/Rel10/ThresholdUTRA.o \
./include/Rel10/TimeAlignmentTimer.o \
./include/Rel10/TimeToTrigger.o \
./include/Rel10/TraceReference-r10.o \
./include/Rel10/TrackingAreaCode.o \
./include/Rel10/TrackingAreaCodeList-r10.o \
./include/Rel10/UE-BasedNetwPerfMeasParameters-r10.o \
./include/Rel10/UE-CapabilityRAT-Container.o \
./include/Rel10/UE-CapabilityRAT-ContainerList.o \
./include/Rel10/UE-CapabilityRequest.o \
./include/Rel10/UE-EUTRA-Capability-v1020-IEs.o \
./include/Rel10/UE-EUTRA-Capability-v920-IEs.o \
./include/Rel10/UE-EUTRA-Capability-v940-IEs.o \
./include/Rel10/UE-EUTRA-Capability.o \
./include/Rel10/UE-TimersAndConstants.o \
./include/Rel10/UECapabilityEnquiry-r8-IEs.o \
./include/Rel10/UECapabilityEnquiry-v8a0-IEs.o \
./include/Rel10/UECapabilityEnquiry.o \
./include/Rel10/UECapabilityInformation-r8-IEs.o \
./include/Rel10/UECapabilityInformation-v8a0-IEs.o \
./include/Rel10/UECapabilityInformation.o \
./include/Rel10/UEInformationRequest-r9-IEs.o \
./include/Rel10/UEInformationRequest-r9.o \
./include/Rel10/UEInformationRequest-v1020-IEs.o \
./include/Rel10/UEInformationRequest-v930-IEs.o \
./include/Rel10/UEInformationResponse-r9-IEs.o \
./include/Rel10/UEInformationResponse-r9.o \
./include/Rel10/UEInformationResponse-v1020-IEs.o \
./include/Rel10/UEInformationResponse-v930-IEs.o \
./include/Rel10/UERadioAccessCapabilityInformation-r8-IEs.o \
./include/Rel10/UERadioAccessCapabilityInformation.o \
./include/Rel10/UL-AM-RLC.o \
./include/Rel10/UL-CCCH-Message.o \
./include/Rel10/UL-CCCH-MessageType.o \
./include/Rel10/UL-CyclicPrefixLength.o \
./include/Rel10/UL-DCCH-Message.o \
./include/Rel10/UL-DCCH-MessageType.o \
./include/Rel10/UL-ReferenceSignalsPUSCH.o \
./include/Rel10/UL-UM-RLC.o \
./include/Rel10/ULHandoverPreparationTransfer-r8-IEs.o \
./include/Rel10/ULHandoverPreparationTransfer-v8a0-IEs.o \
./include/Rel10/ULHandoverPreparationTransfer.o \
./include/Rel10/ULInformationTransfer-r8-IEs.o \
./include/Rel10/ULInformationTransfer-v8a0-IEs.o \
./include/Rel10/ULInformationTransfer.o \
./include/Rel10/UplinkPowerControlCommon-v1020.o \
./include/Rel10/UplinkPowerControlCommon.o \
./include/Rel10/UplinkPowerControlCommonSCell-r10.o \
./include/Rel10/UplinkPowerControlDedicated-v1020.o \
./include/Rel10/UplinkPowerControlDedicated.o \
./include/Rel10/UplinkPowerControlDedicatedSCell-r10.o \
./include/Rel10/VarLogMeasConfig-r10.o \
./include/Rel10/VarLogMeasReport-r10.o \
./include/Rel10/VarMeasConfig.o \
./include/Rel10/VarMeasReport.o \
./include/Rel10/VarMeasReportList.o \
./include/Rel10/VarRLF-Report-r10.o \
./include/Rel10/VarShortMAC-Input.o \
./include/Rel10/asn_SEQUENCE_OF.o \
./include/Rel10/asn_SET_OF.o \
./include/Rel10/asn_codecs_prim.o \
./include/Rel10/ber_decoder.o \
./include/Rel10/ber_tlv_length.o \
./include/Rel10/ber_tlv_tag.o \
./include/Rel10/constr_CHOICE.o \
./include/Rel10/constr_SEQUENCE.o \
./include/Rel10/constr_SEQUENCE_OF.o \
./include/Rel10/constr_SET_OF.o \
./include/Rel10/constr_TYPE.o \
./include/Rel10/constraints.o \
./include/Rel10/der_encoder.o \
./include/Rel10/per_decoder.o \
./include/Rel10/per_encoder.o \
./include/Rel10/per_opentype.o \
./include/Rel10/per_support.o \
./include/Rel10/xer_decoder.o \
./include/Rel10/xer_encoder.o \
./include/Rel10/xer_support.o 

C_DEPS += \
./include/Rel10/AC-BarringConfig.d \
./include/Rel10/AC-BarringConfig1XRTT-r9.d \
./include/Rel10/ARFCN-ValueCDMA2000.d \
./include/Rel10/ARFCN-ValueEUTRA.d \
./include/Rel10/ARFCN-ValueGERAN.d \
./include/Rel10/ARFCN-ValueUTRA.d \
./include/Rel10/AS-Config.d \
./include/Rel10/AS-Context.d \
./include/Rel10/AbsoluteTimeInfo-r10.d \
./include/Rel10/AccessStratumRelease.d \
./include/Rel10/AdditionalReestabInfo.d \
./include/Rel10/AdditionalReestabInfoList.d \
./include/Rel10/AdditionalSI-Info-r9.d \
./include/Rel10/AdditionalSpectrumEmission.d \
./include/Rel10/AllowedMeasBandwidth.d \
./include/Rel10/AntennaInfoCommon.d \
./include/Rel10/AntennaInfoDedicated-r10.d \
./include/Rel10/AntennaInfoDedicated-v920.d \
./include/Rel10/AntennaInfoDedicated.d \
./include/Rel10/AntennaInfoUL-r10.d \
./include/Rel10/AreaConfiguration-r10.d \
./include/Rel10/BCCH-BCH-Message.d \
./include/Rel10/BCCH-BCH-MessageType.d \
./include/Rel10/BCCH-Config.d \
./include/Rel10/BCCH-DL-SCH-Message.d \
./include/Rel10/BCCH-DL-SCH-MessageType.d \
./include/Rel10/BIT_STRING.d \
./include/Rel10/BOOLEAN.d \
./include/Rel10/BandClassInfoCDMA2000.d \
./include/Rel10/BandClassListCDMA2000.d \
./include/Rel10/BandClassPriority1XRTT.d \
./include/Rel10/BandClassPriorityHRPD.d \
./include/Rel10/BandClassPriorityList1XRTT.d \
./include/Rel10/BandClassPriorityListHRPD.d \
./include/Rel10/BandCombinationListEUTRA-r10.d \
./include/Rel10/BandCombinationParameters-r10.d \
./include/Rel10/BandIndicatorGERAN.d \
./include/Rel10/BandInfoEUTRA.d \
./include/Rel10/BandListEUTRA.d \
./include/Rel10/BandParameters-r10.d \
./include/Rel10/BandParametersDL-r10.d \
./include/Rel10/BandParametersUL-r10.d \
./include/Rel10/BandclassCDMA2000.d \
./include/Rel10/BlackCellsToAddMod.d \
./include/Rel10/BlackCellsToAddModList.d \
./include/Rel10/C-RNTI.d \
./include/Rel10/CA-BandwidthClass-r10.d \
./include/Rel10/CA-MIMO-ParametersDL-r10.d \
./include/Rel10/CA-MIMO-ParametersUL-r10.d \
./include/Rel10/CDMA2000-Type.d \
./include/Rel10/CQI-ReportAperiodic-r10.d \
./include/Rel10/CQI-ReportConfig-r10.d \
./include/Rel10/CQI-ReportConfig-v920.d \
./include/Rel10/CQI-ReportConfig.d \
./include/Rel10/CQI-ReportConfigSCell-r10.d \
./include/Rel10/CQI-ReportModeAperiodic.d \
./include/Rel10/CQI-ReportPeriodic-r10.d \
./include/Rel10/CQI-ReportPeriodic.d \
./include/Rel10/CSFB-RegistrationParam1XRTT-v920.d \
./include/Rel10/CSFB-RegistrationParam1XRTT.d \
./include/Rel10/CSFBParametersRequestCDMA2000-r8-IEs.d \
./include/Rel10/CSFBParametersRequestCDMA2000-v8a0-IEs.d \
./include/Rel10/CSFBParametersRequestCDMA2000.d \
./include/Rel10/CSFBParametersResponseCDMA2000-r8-IEs.d \
./include/Rel10/CSFBParametersResponseCDMA2000-v8a0-IEs.d \
./include/Rel10/CSFBParametersResponseCDMA2000.d \
./include/Rel10/CSG-AllowedReportingCells-r9.d \
./include/Rel10/CSG-Identity.d \
./include/Rel10/CSG-ProximityIndicationParameters-r9.d \
./include/Rel10/CSI-RS-Config-r10.d \
./include/Rel10/CandidateCellInfo-r10.d \
./include/Rel10/CandidateCellInfoList-r10.d \
./include/Rel10/CarrierBandwidthEUTRA.d \
./include/Rel10/CarrierFreqCDMA2000.d \
./include/Rel10/CarrierFreqEUTRA.d \
./include/Rel10/CarrierFreqGERAN.d \
./include/Rel10/CarrierFreqListUTRA-FDD.d \
./include/Rel10/CarrierFreqListUTRA-TDD-r10.d \
./include/Rel10/CarrierFreqListUTRA-TDD.d \
./include/Rel10/CarrierFreqUTRA-FDD.d \
./include/Rel10/CarrierFreqUTRA-TDD.d \
./include/Rel10/CarrierFreqsGERAN.d \
./include/Rel10/CarrierFreqsInfoGERAN.d \
./include/Rel10/CarrierFreqsInfoListGERAN.d \
./include/Rel10/CellChangeOrder.d \
./include/Rel10/CellGlobalIdCDMA2000.d \
./include/Rel10/CellGlobalIdEUTRA.d \
./include/Rel10/CellGlobalIdGERAN.d \
./include/Rel10/CellGlobalIdList-r10.d \
./include/Rel10/CellGlobalIdUTRA.d \
./include/Rel10/CellIdentity.d \
./include/Rel10/CellIndex.d \
./include/Rel10/CellIndexList.d \
./include/Rel10/CellInfoGERAN-r9.d \
./include/Rel10/CellInfoListGERAN-r9.d \
./include/Rel10/CellInfoListUTRA-FDD-r9.d \
./include/Rel10/CellInfoListUTRA-TDD-r10.d \
./include/Rel10/CellInfoListUTRA-TDD-r9.d \
./include/Rel10/CellInfoUTRA-FDD-r9.d \
./include/Rel10/CellInfoUTRA-TDD-r10.d \
./include/Rel10/CellInfoUTRA-TDD-r9.d \
./include/Rel10/CellReselectionParametersCDMA2000-v920.d \
./include/Rel10/CellReselectionParametersCDMA2000.d \
./include/Rel10/CellReselectionPriority.d \
./include/Rel10/CellSelectionInfo-v920.d \
./include/Rel10/CellsToAddMod.d \
./include/Rel10/CellsToAddModCDMA2000.d \
./include/Rel10/CellsToAddModList.d \
./include/Rel10/CellsToAddModListCDMA2000.d \
./include/Rel10/CellsToAddModListUTRA-FDD.d \
./include/Rel10/CellsToAddModListUTRA-TDD.d \
./include/Rel10/CellsToAddModUTRA-FDD.d \
./include/Rel10/CellsToAddModUTRA-TDD.d \
./include/Rel10/CellsTriggeredList.d \
./include/Rel10/CommonSF-AllocPatternList-r9.d \
./include/Rel10/CounterCheck-r8-IEs.d \
./include/Rel10/CounterCheck-v8a0-IEs.d \
./include/Rel10/CounterCheck.d \
./include/Rel10/CounterCheckResponse-r8-IEs.d \
./include/Rel10/CounterCheckResponse-v8a0-IEs.d \
./include/Rel10/CounterCheckResponse.d \
./include/Rel10/CountingRequestInfo-r10.d \
./include/Rel10/CountingRequestList-r10.d \
./include/Rel10/CountingResponseInfo-r10.d \
./include/Rel10/CountingResponseList-r10.d \
./include/Rel10/CrossCarrierSchedulingConfig-r10.d \
./include/Rel10/DL-AM-RLC.d \
./include/Rel10/DL-CCCH-Message.d \
./include/Rel10/DL-CCCH-MessageType.d \
./include/Rel10/DL-DCCH-Message.d \
./include/Rel10/DL-DCCH-MessageType.d \
./include/Rel10/DL-UM-RLC.d \
./include/Rel10/DLInformationTransfer-r8-IEs.d \
./include/Rel10/DLInformationTransfer-v8a0-IEs.d \
./include/Rel10/DLInformationTransfer.d \
./include/Rel10/DRB-CountInfo.d \
./include/Rel10/DRB-CountInfoList.d \
./include/Rel10/DRB-CountMSB-Info.d \
./include/Rel10/DRB-CountMSB-InfoList.d \
./include/Rel10/DRB-Identity.d \
./include/Rel10/DRB-ToAddMod.d \
./include/Rel10/DRB-ToAddModList.d \
./include/Rel10/DRB-ToReleaseList.d \
./include/Rel10/DRX-Config.d \
./include/Rel10/DedicatedInfoCDMA2000.d \
./include/Rel10/DedicatedInfoNAS.d \
./include/Rel10/DeltaFList-PUCCH.d \
./include/Rel10/DeltaTxD-OffsetListPUCCH-r10.d \
./include/Rel10/E-CSFB-r9.d \
./include/Rel10/EstablishmentCause.d \
./include/Rel10/ExplicitListOfARFCNs.d \
./include/Rel10/FilterCoefficient.d \
./include/Rel10/FreqPriorityEUTRA.d \
./include/Rel10/FreqPriorityListEUTRA.d \
./include/Rel10/FreqPriorityListUTRA-FDD.d \
./include/Rel10/FreqPriorityListUTRA-TDD.d \
./include/Rel10/FreqPriorityUTRA-FDD.d \
./include/Rel10/FreqPriorityUTRA-TDD.d \
./include/Rel10/FreqsPriorityGERAN.d \
./include/Rel10/FreqsPriorityListGERAN.d \
./include/Rel10/Handover.d \
./include/Rel10/HandoverCommand-r8-IEs.d \
./include/Rel10/HandoverCommand.d \
./include/Rel10/HandoverFromEUTRAPreparationRequest-r8-IEs.d \
./include/Rel10/HandoverFromEUTRAPreparationRequest-v1020-IEs.d \
./include/Rel10/HandoverFromEUTRAPreparationRequest-v890-IEs.d \
./include/Rel10/HandoverFromEUTRAPreparationRequest-v920-IEs.d \
./include/Rel10/HandoverFromEUTRAPreparationRequest.d \
./include/Rel10/HandoverPreparationInformation-r8-IEs.d \
./include/Rel10/HandoverPreparationInformation-v920-IEs.d \
./include/Rel10/HandoverPreparationInformation.d \
./include/Rel10/Hysteresis.d \
./include/Rel10/IMSI-Digit.d \
./include/Rel10/IMSI.d \
./include/Rel10/INTEGER.d \
./include/Rel10/IRAT-ParametersCDMA2000-1XRTT-v1020.d \
./include/Rel10/IRAT-ParametersCDMA2000-1XRTT-v920.d \
./include/Rel10/IRAT-ParametersCDMA2000-1XRTT.d \
./include/Rel10/IRAT-ParametersCDMA2000-HRPD.d \
./include/Rel10/IRAT-ParametersGERAN-v920.d \
./include/Rel10/IRAT-ParametersGERAN.d \
./include/Rel10/IRAT-ParametersUTRA-FDD.d \
./include/Rel10/IRAT-ParametersUTRA-TDD-v1020.d \
./include/Rel10/IRAT-ParametersUTRA-TDD128.d \
./include/Rel10/IRAT-ParametersUTRA-TDD384.d \
./include/Rel10/IRAT-ParametersUTRA-TDD768.d \
./include/Rel10/IRAT-ParametersUTRA-v920.d \
./include/Rel10/IdleModeMobilityControlInfo.d \
./include/Rel10/InitialUE-Identity.d \
./include/Rel10/InterFreqBandInfo.d \
./include/Rel10/InterFreqBandList.d \
./include/Rel10/InterFreqBlackCellList.d \
./include/Rel10/InterFreqCarrierFreqInfo.d \
./include/Rel10/InterFreqCarrierFreqList.d \
./include/Rel10/InterFreqNeighCellInfo.d \
./include/Rel10/InterFreqNeighCellList.d \
./include/Rel10/InterFreqRSTDMeasurementIndication-r10-IEs.d \
./include/Rel10/InterFreqRSTDMeasurementIndication-r10.d \
./include/Rel10/InterRAT-BandInfo.d \
./include/Rel10/InterRAT-BandList.d \
./include/Rel10/IntraFreqBlackCellList.d \
./include/Rel10/IntraFreqNeighCellInfo.d \
./include/Rel10/IntraFreqNeighCellList.d \
./include/Rel10/Key-eNodeB-Star.d \
./include/Rel10/LocationInfo-r10.d \
./include/Rel10/LogMeasInfo-r10.d \
./include/Rel10/LogMeasInfoList-r10.d \
./include/Rel10/LogMeasReport-r10.d \
./include/Rel10/LoggedMeasurementConfiguration-r10-IEs.d \
./include/Rel10/LoggedMeasurementConfiguration-r10.d \
./include/Rel10/LoggingDuration-r10.d \
./include/Rel10/LoggingInterval-r10.d \
./include/Rel10/LogicalChannelConfig.d \
./include/Rel10/MAC-MainConfig.d \
./include/Rel10/MBMS-NotificationConfig-r9.d \
./include/Rel10/MBMS-SessionInfo-r9.d \
./include/Rel10/MBMS-SessionInfoList-r9.d \
./include/Rel10/MBMSCountingRequest-r10.d \
./include/Rel10/MBMSCountingResponse-r10-IEs.d \
./include/Rel10/MBMSCountingResponse-r10.d \
./include/Rel10/MBSFN-AreaInfo-r9.d \
./include/Rel10/MBSFN-AreaInfoList-r9.d \
./include/Rel10/MBSFN-SubframeConfig.d \
./include/Rel10/MBSFN-SubframeConfigList.d \
./include/Rel10/MBSFNAreaConfiguration-r9.d \
./include/Rel10/MBSFNAreaConfiguration-v930-IEs.d \
./include/Rel10/MCC-MNC-Digit.d \
./include/Rel10/MCC.d \
./include/Rel10/MCCH-Message.d \
./include/Rel10/MCCH-MessageType.d \
./include/Rel10/MIMO-CapabilityDL-r10.d \
./include/Rel10/MIMO-CapabilityUL-r10.d \
./include/Rel10/MMEC.d \
./include/Rel10/MNC.d \
./include/Rel10/MasterInformationBlock.d \
./include/Rel10/MeasConfig.d \
./include/Rel10/MeasCycleSCell-r10.d \
./include/Rel10/MeasGapConfig.d \
./include/Rel10/MeasId.d \
./include/Rel10/MeasIdToAddMod.d \
./include/Rel10/MeasIdToAddModList.d \
./include/Rel10/MeasIdToRemoveList.d \
./include/Rel10/MeasObjectCDMA2000.d \
./include/Rel10/MeasObjectEUTRA.d \
./include/Rel10/MeasObjectGERAN.d \
./include/Rel10/MeasObjectId.d \
./include/Rel10/MeasObjectToAddMod.d \
./include/Rel10/MeasObjectToAddModList.d \
./include/Rel10/MeasObjectToRemoveList.d \
./include/Rel10/MeasObjectUTRA.d \
./include/Rel10/MeasParameters-v1020.d \
./include/Rel10/MeasParameters.d \
./include/Rel10/MeasResult2CDMA2000-r9.d \
./include/Rel10/MeasResult2EUTRA-r9.d \
./include/Rel10/MeasResult2UTRA-r9.d \
./include/Rel10/MeasResultCDMA2000.d \
./include/Rel10/MeasResultEUTRA.d \
./include/Rel10/MeasResultForECID-r9.d \
./include/Rel10/MeasResultGERAN.d \
./include/Rel10/MeasResultList2CDMA2000-r9.d \
./include/Rel10/MeasResultList2EUTRA-r9.d \
./include/Rel10/MeasResultList2GERAN-r10.d \
./include/Rel10/MeasResultList2UTRA-r9.d \
./include/Rel10/MeasResultListCDMA2000.d \
./include/Rel10/MeasResultListEUTRA.d \
./include/Rel10/MeasResultListGERAN.d \
./include/Rel10/MeasResultListUTRA.d \
./include/Rel10/MeasResultServFreq-r10.d \
./include/Rel10/MeasResultServFreqList-r10.d \
./include/Rel10/MeasResultUTRA.d \
./include/Rel10/MeasResults.d \
./include/Rel10/MeasResultsCDMA2000.d \
./include/Rel10/MeasSubframeCellList-r10.d \
./include/Rel10/MeasSubframePattern-r10.d \
./include/Rel10/MeasSubframePatternConfigNeigh-r10.d \
./include/Rel10/MeasSubframePatternPCell-r10.d \
./include/Rel10/MeasurementReport-r8-IEs.d \
./include/Rel10/MeasurementReport-v8a0-IEs.d \
./include/Rel10/MeasurementReport.d \
./include/Rel10/MobilityControlInfo.d \
./include/Rel10/MobilityFromEUTRACommand-r8-IEs.d \
./include/Rel10/MobilityFromEUTRACommand-r9-IEs.d \
./include/Rel10/MobilityFromEUTRACommand-v8a0-IEs.d \
./include/Rel10/MobilityFromEUTRACommand-v8d0-IEs.d \
./include/Rel10/MobilityFromEUTRACommand-v930-IEs.d \
./include/Rel10/MobilityFromEUTRACommand-v960-IEs.d \
./include/Rel10/MobilityFromEUTRACommand.d \
./include/Rel10/MobilityParametersCDMA2000.d \
./include/Rel10/MobilityStateParameters.d \
./include/Rel10/N1PUCCH-AN-CS-r10.d \
./include/Rel10/N1PUCCH-AN-PersistentList.d \
./include/Rel10/NULL.d \
./include/Rel10/NativeEnumerated.d \
./include/Rel10/NativeInteger.d \
./include/Rel10/NeighCellCDMA2000-v920.d \
./include/Rel10/NeighCellCDMA2000.d \
./include/Rel10/NeighCellConfig.d \
./include/Rel10/NeighCellListCDMA2000-v920.d \
./include/Rel10/NeighCellListCDMA2000.d \
./include/Rel10/NeighCellSI-AcquisitionParameters-r9.d \
./include/Rel10/NeighCellsPerBandclassCDMA2000-v920.d \
./include/Rel10/NeighCellsPerBandclassCDMA2000.d \
./include/Rel10/NeighCellsPerBandclassListCDMA2000-v920.d \
./include/Rel10/NeighCellsPerBandclassListCDMA2000.d \
./include/Rel10/NextHopChainingCount.d \
./include/Rel10/NonContiguousUL-RA-WithinCC-List-r10.d \
./include/Rel10/NonContiguousUL-RA-WithinCC-r10.d \
./include/Rel10/OCTET_STRING.d \
./include/Rel10/OtherConfig-r9.d \
./include/Rel10/P-Max.d \
./include/Rel10/PCCH-Config.d \
./include/Rel10/PCCH-Message.d \
./include/Rel10/PCCH-MessageType.d \
./include/Rel10/PDCP-Config.d \
./include/Rel10/PDCP-Parameters.d \
./include/Rel10/PDSCH-ConfigCommon.d \
./include/Rel10/PDSCH-ConfigDedicated.d \
./include/Rel10/PHICH-Config.d \
./include/Rel10/PLMN-Identity.d \
./include/Rel10/PLMN-IdentityInfo.d \
./include/Rel10/PLMN-IdentityList.d \
./include/Rel10/PLMN-IdentityList2.d \
./include/Rel10/PMCH-Config-r9.d \
./include/Rel10/PMCH-Info-r9.d \
./include/Rel10/PMCH-InfoList-r9.d \
./include/Rel10/PRACH-Config.d \
./include/Rel10/PRACH-ConfigInfo.d \
./include/Rel10/PRACH-ConfigSCell-r10.d \
./include/Rel10/PRACH-ConfigSIB.d \
./include/Rel10/PUCCH-ConfigCommon.d \
./include/Rel10/PUCCH-ConfigDedicated-v1020.d \
./include/Rel10/PUCCH-ConfigDedicated.d \
./include/Rel10/PUSCH-ConfigCommon.d \
./include/Rel10/PUSCH-ConfigDedicated-v1020.d \
./include/Rel10/PUSCH-ConfigDedicated.d \
./include/Rel10/PUSCH-ConfigDedicatedSCell-r10.d \
./include/Rel10/Paging-v890-IEs.d \
./include/Rel10/Paging-v920-IEs.d \
./include/Rel10/Paging.d \
./include/Rel10/PagingRecord.d \
./include/Rel10/PagingRecordList.d \
./include/Rel10/PagingUE-Identity.d \
./include/Rel10/PhyLayerParameters-v1020.d \
./include/Rel10/PhyLayerParameters-v920.d \
./include/Rel10/PhyLayerParameters.d \
./include/Rel10/PhysCellId.d \
./include/Rel10/PhysCellIdCDMA2000.d \
./include/Rel10/PhysCellIdGERAN.d \
./include/Rel10/PhysCellIdListCDMA2000-v920.d \
./include/Rel10/PhysCellIdListCDMA2000.d \
./include/Rel10/PhysCellIdRange.d \
./include/Rel10/PhysCellIdRangeUTRA-FDD-r9.d \
./include/Rel10/PhysCellIdRangeUTRA-FDDList-r9.d \
./include/Rel10/PhysCellIdUTRA-FDD.d \
./include/Rel10/PhysCellIdUTRA-TDD.d \
./include/Rel10/PhysicalConfigDedicated.d \
./include/Rel10/PhysicalConfigDedicatedSCell-r10.d \
./include/Rel10/PollByte.d \
./include/Rel10/PollPDU.d \
./include/Rel10/PreRegistrationInfoHRPD.d \
./include/Rel10/PreRegistrationZoneIdHRPD.d \
./include/Rel10/PresenceAntennaPort1.d \
./include/Rel10/ProximityIndication-r9-IEs.d \
./include/Rel10/ProximityIndication-r9.d \
./include/Rel10/ProximityIndication-v930-IEs.d \
./include/Rel10/Q-OffsetRange.d \
./include/Rel10/Q-OffsetRangeInterRAT.d \
./include/Rel10/Q-QualMin-r9.d \
./include/Rel10/Q-RxLevMin.d \
./include/Rel10/QuantityConfig.d \
./include/Rel10/QuantityConfigCDMA2000.d \
./include/Rel10/QuantityConfigEUTRA.d \
./include/Rel10/QuantityConfigGERAN.d \
./include/Rel10/QuantityConfigUTRA-v1020.d \
./include/Rel10/QuantityConfigUTRA.d \
./include/Rel10/RACH-ConfigCommon.d \
./include/Rel10/RACH-ConfigDedicated.d \
./include/Rel10/RAND-CDMA2000.d \
./include/Rel10/RAT-Type.d \
./include/Rel10/RF-Parameters-v1020.d \
./include/Rel10/RF-Parameters.d \
./include/Rel10/RLC-Config.d \
./include/Rel10/RLF-Report-r9.d \
./include/Rel10/RLF-TimersAndConstants-r9.d \
./include/Rel10/RN-SubframeConfig-r10.d \
./include/Rel10/RN-SystemInfo-r10.d \
./include/Rel10/RNReconfiguration-r10-IEs.d \
./include/Rel10/RNReconfiguration-r10.d \
./include/Rel10/RNReconfigurationComplete-r10-IEs.d \
./include/Rel10/RNReconfigurationComplete-r10.d \
./include/Rel10/RRC-TransactionIdentifier.d \
./include/Rel10/RRCConnectionReconfiguration-r8-IEs.d \
./include/Rel10/RRCConnectionReconfiguration-v1020-IEs.d \
./include/Rel10/RRCConnectionReconfiguration-v890-IEs.d \
./include/Rel10/RRCConnectionReconfiguration-v920-IEs.d \
./include/Rel10/RRCConnectionReconfiguration.d \
./include/Rel10/RRCConnectionReconfigurationComplete-r8-IEs.d \
./include/Rel10/RRCConnectionReconfigurationComplete-v1020-IEs.d \
./include/Rel10/RRCConnectionReconfigurationComplete-v8a0-IEs.d \
./include/Rel10/RRCConnectionReconfigurationComplete.d \
./include/Rel10/RRCConnectionReestablishment-r8-IEs.d \
./include/Rel10/RRCConnectionReestablishment-v8a0-IEs.d \
./include/Rel10/RRCConnectionReestablishment.d \
./include/Rel10/RRCConnectionReestablishmentComplete-r8-IEs.d \
./include/Rel10/RRCConnectionReestablishmentComplete-v1020-IEs.d \
./include/Rel10/RRCConnectionReestablishmentComplete-v8a0-IEs.d \
./include/Rel10/RRCConnectionReestablishmentComplete-v920-IEs.d \
./include/Rel10/RRCConnectionReestablishmentComplete.d \
./include/Rel10/RRCConnectionReestablishmentReject-r8-IEs.d \
./include/Rel10/RRCConnectionReestablishmentReject-v8a0-IEs.d \
./include/Rel10/RRCConnectionReestablishmentReject.d \
./include/Rel10/RRCConnectionReestablishmentRequest-r8-IEs.d \
./include/Rel10/RRCConnectionReestablishmentRequest.d \
./include/Rel10/RRCConnectionReject-r8-IEs.d \
./include/Rel10/RRCConnectionReject-v1020-IEs.d \
./include/Rel10/RRCConnectionReject-v8a0-IEs.d \
./include/Rel10/RRCConnectionReject.d \
./include/Rel10/RRCConnectionRelease-r8-IEs.d \
./include/Rel10/RRCConnectionRelease-v1020-IEs.d \
./include/Rel10/RRCConnectionRelease-v890-IEs.d \
./include/Rel10/RRCConnectionRelease-v920-IEs.d \
./include/Rel10/RRCConnectionRelease.d \
./include/Rel10/RRCConnectionRequest-r8-IEs.d \
./include/Rel10/RRCConnectionRequest.d \
./include/Rel10/RRCConnectionSetup-r8-IEs.d \
./include/Rel10/RRCConnectionSetup-v8a0-IEs.d \
./include/Rel10/RRCConnectionSetup.d \
./include/Rel10/RRCConnectionSetupComplete-r8-IEs.d \
./include/Rel10/RRCConnectionSetupComplete-v1020-IEs.d \
./include/Rel10/RRCConnectionSetupComplete-v8a0-IEs.d \
./include/Rel10/RRCConnectionSetupComplete.d \
./include/Rel10/RRM-Config.d \
./include/Rel10/RSRP-Range.d \
./include/Rel10/RSRQ-Range.d \
./include/Rel10/RSTD-InterFreqInfo-r10.d \
./include/Rel10/RSTD-InterFreqInfoList-r10.d \
./include/Rel10/RadioResourceConfigCommon.d \
./include/Rel10/RadioResourceConfigCommonSCell-r10.d \
./include/Rel10/RadioResourceConfigCommonSIB.d \
./include/Rel10/RadioResourceConfigDedicated.d \
./include/Rel10/RadioResourceConfigDedicatedSCell-r10.d \
./include/Rel10/RedirectedCarrierInfo.d \
./include/Rel10/ReestabUE-Identity.d \
./include/Rel10/ReestablishmentCause.d \
./include/Rel10/ReestablishmentInfo.d \
./include/Rel10/RegisteredMME.d \
./include/Rel10/ReleaseCause.d \
./include/Rel10/ReportConfigEUTRA.d \
./include/Rel10/ReportConfigId.d \
./include/Rel10/ReportConfigInterRAT.d \
./include/Rel10/ReportConfigToAddMod.d \
./include/Rel10/ReportConfigToAddModList.d \
./include/Rel10/ReportConfigToRemoveList.d \
./include/Rel10/ReportInterval.d \
./include/Rel10/ReportProximityConfig-r9.d \
./include/Rel10/ReselectionThreshold.d \
./include/Rel10/ReselectionThresholdQ-r9.d \
./include/Rel10/S-TMSI.d \
./include/Rel10/SCellIndex-r10.d \
./include/Rel10/SCellToAddMod-r10.d \
./include/Rel10/SCellToAddModList-r10.d \
./include/Rel10/SCellToReleaseList-r10.d \
./include/Rel10/SI-OrPSI-GERAN.d \
./include/Rel10/SIB-MappingInfo.d \
./include/Rel10/SIB-Type.d \
./include/Rel10/SN-FieldLength.d \
./include/Rel10/SON-Parameters-r9.d \
./include/Rel10/SPS-Config.d \
./include/Rel10/SPS-ConfigDL.d \
./include/Rel10/SPS-ConfigUL.d \
./include/Rel10/SRB-ToAddMod.d \
./include/Rel10/SRB-ToAddModList.d \
./include/Rel10/SRS-ConfigAp-r10.d \
./include/Rel10/SchedulingInfo.d \
./include/Rel10/SchedulingInfoList.d \
./include/Rel10/SchedulingRequestConfig-v1020.d \
./include/Rel10/SchedulingRequestConfig.d \
./include/Rel10/SecondaryPreRegistrationZoneIdListHRPD.d \
./include/Rel10/SecurityAlgorithmConfig.d \
./include/Rel10/SecurityConfigHO.d \
./include/Rel10/SecurityConfigSMC.d \
./include/Rel10/SecurityModeCommand-r8-IEs.d \
./include/Rel10/SecurityModeCommand-v8a0-IEs.d \
./include/Rel10/SecurityModeCommand.d \
./include/Rel10/SecurityModeComplete-r8-IEs.d \
./include/Rel10/SecurityModeComplete-v8a0-IEs.d \
./include/Rel10/SecurityModeComplete.d \
./include/Rel10/SecurityModeFailure-r8-IEs.d \
./include/Rel10/SecurityModeFailure-v8a0-IEs.d \
./include/Rel10/SecurityModeFailure.d \
./include/Rel10/ServCellIndex-r10.d \
./include/Rel10/ShortMAC-I.d \
./include/Rel10/SoundingRS-UL-ConfigCommon.d \
./include/Rel10/SoundingRS-UL-ConfigDedicated-v1020.d \
./include/Rel10/SoundingRS-UL-ConfigDedicated.d \
./include/Rel10/SoundingRS-UL-ConfigDedicatedAperiodic-r10.d \
./include/Rel10/SpeedStateScaleFactors.d \
./include/Rel10/SupportedBandCombination-r10.d \
./include/Rel10/SupportedBandEUTRA.d \
./include/Rel10/SupportedBandGERAN.d \
./include/Rel10/SupportedBandList1XRTT.d \
./include/Rel10/SupportedBandListEUTRA.d \
./include/Rel10/SupportedBandListGERAN.d \
./include/Rel10/SupportedBandListHRPD.d \
./include/Rel10/SupportedBandListUTRA-FDD.d \
./include/Rel10/SupportedBandListUTRA-TDD128.d \
./include/Rel10/SupportedBandListUTRA-TDD384.d \
./include/Rel10/SupportedBandListUTRA-TDD768.d \
./include/Rel10/SupportedBandUTRA-FDD.d \
./include/Rel10/SupportedBandUTRA-TDD128.d \
./include/Rel10/SupportedBandUTRA-TDD384.d \
./include/Rel10/SupportedBandUTRA-TDD768.d \
./include/Rel10/SystemInfoListGERAN.d \
./include/Rel10/SystemInformation-r8-IEs.d \
./include/Rel10/SystemInformation-v8a0-IEs.d \
./include/Rel10/SystemInformation.d \
./include/Rel10/SystemInformationBlockType1-v890-IEs.d \
./include/Rel10/SystemInformationBlockType1-v920-IEs.d \
./include/Rel10/SystemInformationBlockType1.d \
./include/Rel10/SystemInformationBlockType10.d \
./include/Rel10/SystemInformationBlockType11.d \
./include/Rel10/SystemInformationBlockType12-r9.d \
./include/Rel10/SystemInformationBlockType13-r9.d \
./include/Rel10/SystemInformationBlockType2.d \
./include/Rel10/SystemInformationBlockType3.d \
./include/Rel10/SystemInformationBlockType4.d \
./include/Rel10/SystemInformationBlockType5.d \
./include/Rel10/SystemInformationBlockType6.d \
./include/Rel10/SystemInformationBlockType7.d \
./include/Rel10/SystemInformationBlockType8.d \
./include/Rel10/SystemInformationBlockType9.d \
./include/Rel10/SystemTimeInfoCDMA2000.d \
./include/Rel10/T-PollRetransmit.d \
./include/Rel10/T-Reordering.d \
./include/Rel10/T-Reselection.d \
./include/Rel10/T-StatusProhibit.d \
./include/Rel10/TDD-Config.d \
./include/Rel10/TMGI-r9.d \
./include/Rel10/TPC-Index.d \
./include/Rel10/TPC-PDCCH-Config.d \
./include/Rel10/ThresholdCDMA2000.d \
./include/Rel10/ThresholdEUTRA.d \
./include/Rel10/ThresholdGERAN.d \
./include/Rel10/ThresholdUTRA.d \
./include/Rel10/TimeAlignmentTimer.d \
./include/Rel10/TimeToTrigger.d \
./include/Rel10/TraceReference-r10.d \
./include/Rel10/TrackingAreaCode.d \
./include/Rel10/TrackingAreaCodeList-r10.d \
./include/Rel10/UE-BasedNetwPerfMeasParameters-r10.d \
./include/Rel10/UE-CapabilityRAT-Container.d \
./include/Rel10/UE-CapabilityRAT-ContainerList.d \
./include/Rel10/UE-CapabilityRequest.d \
./include/Rel10/UE-EUTRA-Capability-v1020-IEs.d \
./include/Rel10/UE-EUTRA-Capability-v920-IEs.d \
./include/Rel10/UE-EUTRA-Capability-v940-IEs.d \
./include/Rel10/UE-EUTRA-Capability.d \
./include/Rel10/UE-TimersAndConstants.d \
./include/Rel10/UECapabilityEnquiry-r8-IEs.d \
./include/Rel10/UECapabilityEnquiry-v8a0-IEs.d \
./include/Rel10/UECapabilityEnquiry.d \
./include/Rel10/UECapabilityInformation-r8-IEs.d \
./include/Rel10/UECapabilityInformation-v8a0-IEs.d \
./include/Rel10/UECapabilityInformation.d \
./include/Rel10/UEInformationRequest-r9-IEs.d \
./include/Rel10/UEInformationRequest-r9.d \
./include/Rel10/UEInformationRequest-v1020-IEs.d \
./include/Rel10/UEInformationRequest-v930-IEs.d \
./include/Rel10/UEInformationResponse-r9-IEs.d \
./include/Rel10/UEInformationResponse-r9.d \
./include/Rel10/UEInformationResponse-v1020-IEs.d \
./include/Rel10/UEInformationResponse-v930-IEs.d \
./include/Rel10/UERadioAccessCapabilityInformation-r8-IEs.d \
./include/Rel10/UERadioAccessCapabilityInformation.d \
./include/Rel10/UL-AM-RLC.d \
./include/Rel10/UL-CCCH-Message.d \
./include/Rel10/UL-CCCH-MessageType.d \
./include/Rel10/UL-CyclicPrefixLength.d \
./include/Rel10/UL-DCCH-Message.d \
./include/Rel10/UL-DCCH-MessageType.d \
./include/Rel10/UL-ReferenceSignalsPUSCH.d \
./include/Rel10/UL-UM-RLC.d \
./include/Rel10/ULHandoverPreparationTransfer-r8-IEs.d \
./include/Rel10/ULHandoverPreparationTransfer-v8a0-IEs.d \
./include/Rel10/ULHandoverPreparationTransfer.d \
./include/Rel10/ULInformationTransfer-r8-IEs.d \
./include/Rel10/ULInformationTransfer-v8a0-IEs.d \
./include/Rel10/ULInformationTransfer.d \
./include/Rel10/UplinkPowerControlCommon-v1020.d \
./include/Rel10/UplinkPowerControlCommon.d \
./include/Rel10/UplinkPowerControlCommonSCell-r10.d \
./include/Rel10/UplinkPowerControlDedicated-v1020.d \
./include/Rel10/UplinkPowerControlDedicated.d \
./include/Rel10/UplinkPowerControlDedicatedSCell-r10.d \
./include/Rel10/VarLogMeasConfig-r10.d \
./include/Rel10/VarLogMeasReport-r10.d \
./include/Rel10/VarMeasConfig.d \
./include/Rel10/VarMeasReport.d \
./include/Rel10/VarMeasReportList.d \
./include/Rel10/VarRLF-Report-r10.d \
./include/Rel10/VarShortMAC-Input.d \
./include/Rel10/asn_SEQUENCE_OF.d \
./include/Rel10/asn_SET_OF.d \
./include/Rel10/asn_codecs_prim.d \
./include/Rel10/ber_decoder.d \
./include/Rel10/ber_tlv_length.d \
./include/Rel10/ber_tlv_tag.d \
./include/Rel10/constr_CHOICE.d \
./include/Rel10/constr_SEQUENCE.d \
./include/Rel10/constr_SEQUENCE_OF.d \
./include/Rel10/constr_SET_OF.d \
./include/Rel10/constr_TYPE.d \
./include/Rel10/constraints.d \
./include/Rel10/der_encoder.d \
./include/Rel10/per_decoder.d \
./include/Rel10/per_encoder.d \
./include/Rel10/per_opentype.d \
./include/Rel10/per_support.d \
./include/Rel10/xer_decoder.d \
./include/Rel10/xer_encoder.d \
./include/Rel10/xer_support.d 


# Each subdirectory must supply rules for building sources it contributes
include/Rel10/%.o: ../include/Rel10/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I/home/user/alam_development/common_header -I/home/user/alam_development/pdcp_load_test/include -I/home/user/alam_development/pdcp_load_test/include/PDCP_v10.1.0 -I/home/user/alam_development/pdcp_load_test/include/Rel10 -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


